### PR TITLE
master-qa-22189

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-22189

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
I got a rebase error on this one and am not sure how to resolve it. Can you resend this?

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
@brianchiu  rebased :)

**Comment by brianchiu** [comment]
@kmaria 
Thanks!

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/36214

**Pull request closed without merging**
