### PR TITLE
LRQA-29424 | master

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-29424

### CODE REVIEW

**Comment by brianchiu** [comment]
@kmaria 
I got a rebase error. Could you resend?

```
First, rewinding head to replay your work on top of it...
Applying: LRQA-29424 Split up test case file by similar setups
Using index info to reconstruct a base tree...
M       portal-web/test/functional/com/liferay/portalweb/tests/enduser/wcm/staging/usecase/StagingUsecase.testcase
.git/rebase-apply/patch:7: trailing whitespace.
<definition component-name="portal-staging">
.git/rebase-apply/patch:8: trailing whitespace.
        <property name="portal.release" value="true" />
.git/rebase-apply/patch:9: trailing whitespace.
        <property name="testray.main.component.name" value="Staging" />
.git/rebase-apply/patch:10: trailing whitespace.

.git/rebase-apply/patch:11: trailing whitespace.
        <set-up>
warning: squelched 3701 whitespace errors
warning: 3706 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging portal-web/test/functional/com/liferay/portalweb/tests/enduser/wcm/staging/usecase/Staging.testcase
CONFLICT (add/add): Merge conflict in portal-web/test/functional/com/liferay/portalweb/tests/enduser/wcm/staging/usecase/Staging.testcase
error: Failed to merge in the changes.
Patch failed at 0001 LRQA-29424 Split up test case file by similar setups
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
What change were you making in this pull? I opened up the commit in smartgit and it detected no changes (even though it said the files were modified). The commit looks weird in Github too.

https://github.com/brianchiu/liferay-portal/pull/1549/commits/56659b9c711005c6fd4127bdc3546d2a999258cc

**Comment by kmaria** [comment]
@brianchiu added the new property and changed the line delimiters from windows to unix

**Comment by vicnate5** [comment]
@kmaria Thanks for fixing the line delimiters! It gave me the idea to check and convert the rest of our test files to unix format.
See https://github.com/brianchiu/liferay-portal/issues/1552 @brianchiu

**Comment by brianchiu** [comment]
Sounds good. In that case, I'm going to close this pull and push in the other one.

**Pull request closed without merging**
