### PR TITLE
master-qa-19537

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-19537

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5 
Going to hold off on this until after https://github.com/brianchandotcom/liferay-portal/pull/32653 goes in. Because this makes a change to one of the old path files.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@vicnate5 
Can you rebase this? I wasn't able to get it rebase (even though it says it passed...)

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@brianchiu Fixed it :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32785

**Pull request closed without merging**
