### PR TITLE
LPS-85619 Don't create default site navigation menus

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianchiu @kyle-miho,

We've decided to make some changes on navigation menus, one of them is not create the default menus anymore, Could you please take a look at it?, maybe some tests are broken or some funcionality.

Please see: https://issues.liferay.com/browse/LPS-85618 for more details. (Actually, there aren't more details, hehe, but we are going to add all the information there)

Thanks!!,
Eudaldo

**Comment by brianchiu** [comment]
@ealonso Got it. Thanks! I'll check it out.

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/63338

**Pull request closed without merging**
