### PR TITLE
LPS-96809 Rename to reflect changes

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pull looks good. No automated test failures related to it, and I manually tested the fix (and it works).

**Comment by brianchiu** [comment]
PR submitted to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74784

**Pull request closed without merging**
