### PR TITLE
LPS-96679 Comparate generated html with jsoup

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@pavel-savinov I think there's an issue in this pull too :(

https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/276866//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanGradleFiles

**Comment by jkappler** [comment]
CI:close

**Pull request closed without merging**
