### PR TITLE
LPS-90279 Don't show contextual sidebar on the small screens

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @brianchiu, with this pull sidebar doesn't overflow the fields, but at the same time it doesn't show up in the mobile screen size. In one of the tech tasks of this Story we are going to create a toolbar which allows to show/hide the sidebar. Thanks!

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@pavel-savinov Got it!

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
ci:test

**Comment by brianchiu** [comment]
pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68348

**Pull request closed without merging**
