### PR TITLE
LPS-91286 Fix integration test

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@brianchiu, this is the same PR that was sent to BChan, just want to check the tests

**Comment by brianchiu** [comment]
Ok. This looks good.

**Comment by brianchiu** [comment]
PR sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69062

**Comment by brianchiu** [comment]
Oops. PR was sent to BChan. I closed mine.

**Pull request closed without merging**
