### PR TITLE
LPS-81405 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-81405

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@brianchiu I did not need to fix usage of adding "Content Pages", because we have no tests yet that add "Content Pages" (usually we create page templates then use them as a basis for content pages). I fixed the naming of Content -> Content Pages regardless. Layout -> Widget Pages should be all good.

**Comment by kyle-miho** [comment]
@ealonso

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/59027

**Pull request closed without merging**
