### PR TITLE
master-vw-97

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-19928

@brianchiu Pushed this to you cuz it was a pretty big change, wanted more eyes on it.

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5 @ctampoya 
Thanks for checking in.

I have some questions that maybe you can just explain on Monday in person.
* How come you're clicking on repeating day of the week when you're repeating monthly?
```
		<if>
			<equals arg1="${frequency}" arg2="Monthly" />
			<then>
				<execute function="Click" locator1="CalendarEditEvent#REPEAT_REPEAT_ON_DAY_OF_THE_WEEK_RADIO" />
			</then>
		</if>
```
* How come in "setRepeatingYearly" you call "selectRepeatFrequency" and pass in a frequency value? Shouldn't you just pass in "yearly" or something like that?
```
	<command name="setRepeatingYearly">
		<execute macro="CalendarEvent#gotoRepeatConfiguration" />

		<execute macro="CalendarEvent#selectRepeatFrequency">
			<var name="frequency" value="${frequency}" />
		</execute>
```
* What are the repeating month positions and what do the values mean?

**Comment by brianchiu** [comment]
ci:retest

**Comment by vicnate5** [comment]
@brianchiu @ctampoya I agree the frequency should be hard-coded for `setRepeatingYearly`

**Comment by ctampoya** [comment]
@BChiu When we repeat Day of the Week, it will create an event that repeats: "Monthly, On the First Monday." So the "First" is the position value and it gets auto populated with the current day the calendar event is created. For the "setRepeatingYearly" macro, I agree with you, it would make more sense to pass in the value as "Yearly" instead of passing in the frequency value since that macro is explicitly only for Yearly repeating events. That macro was copied and pasted from another macro, so I didn't change the way the variable was passed.

**Comment by brianchiu** [comment]
@vicnate5 @ctampoya 
So, I should just replace
```
<var name="frequency" value="${frequency}" />
```
with
```
<var name="frequency" value="Yearly" />
```
^ Like that?

**Comment by vicnate5** [comment]
@brianchiu Yes, in setRepeatingYearly macro

``` 
<command name="setRepeatingYearly">
        <execute macro="CalendarEvent#gotoRepeatConfiguration" />

        <execute macro="CalendarEvent#selectRepeatFrequency">
            <var name="frequency" value="Yearly" />
        </execute>
```

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Note: I'm running retest for testing purposes. I want to see if a particular inconsistent failure will occur.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33161

**Pull request closed without merging**
