### PR TITLE
LPS-92996 Adds test for ddm template that is used as a mapping field

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
PR sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70970

**Pull request closed without merging**
