### PR TITLE
LRQA-33005 | LRQA-33007 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-33005
https://issues.liferay.com/browse/LRQA-33007

cc @vicnate5 this fixes the `${structureFieldName}` substitutions.

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by vicnate5** [comment]
Thanks! Looks like a was a bigger change, sorry for breaking it.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by brianchiu** [comment]
Testing it here:
https://github.com/brianchiu/liferay-portal/pull/1582

**Pull request closed without merging**
