### PR TITLE
master-rs-45

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-26854

### CODE REVIEW

**Comment by brianchiu** [comment]
@GinsonRen 
I asked Brian Lee if this was needed in 7.0.x. In the future, you can either send me a pull for 7.0.x or tell me that this is needed in 7.0.x also. Otherwise, I won't know.

**Comment by brianchiu** [comment]
Actually... I ran into a rebase error.

@GinsonRen @xbrianlee
Is this change still needed?

**Comment by GinsonRen** [comment]
@brianchiu Sure, I will.

**Comment by xbrianlee** [comment]
I don't think we need this fix anymore. The "Other Site..." menu item always seems to show up regardless of if the parent site has any child sites. I updated `AssetPublisherPortlet#viewConfigureSiteScopeContentSharingPG` in 4c645ca1e13313cc05d707c79e19e0006be0b8b2.

**Comment by brianchiu** [comment]
Alright.

**Pull request closed without merging**
