### PR TITLE
master-qa-14452

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-14452

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Closing for now. There may be a potential issue with the mobile tests.

**Comment by kenjiheigel** [comment]
Issues weren't caused by this.

**Comment by kenjiheigel** [comment]
Pulls have been sent for ee-6.2.x, ee-6.2.10, ee-6.1.x and ee-6.1.30 (cannot cherry pick from master to the ee branches):
https://github.com/brianchiu/liferay-portal-ee/pull/3587 (ee-6.2.x)
https://github.com/brianchiu/liferay-portal-ee/pull/3588 (ee-6.2.10)
https://github.com/brianchiu/liferay-portal-ee/pull/3589 (ee-6.1.x)
https://github.com/brianchiu/liferay-portal-ee/pull/3590 (ee-6.1.30)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal-ee/pull/9316
https://github.com/brianchandotcom/liferay-portal-ee/pull/9315
https://github.com/brianchandotcom/liferay-portal-ee/pull/9314
https://github.com/brianchandotcom/liferay-portal-ee/pull/9313
https://github.com/brianchandotcom/liferay-portal/pull/25061

**Pull request closed without merging**
