### PR TITLE
LPS-89170

### PR DESCRIPTION
**Pull request by danielkocsis**
Hi @brianchiu,

BChan asked me to send this PR to you to check the CI results. It has a lot of failures, but those doesn't seem related and varies the number/type on a daily basis. 

Could you please check this for me and let me know if we missed anything and still has related failures?

thanks,
Daniel

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:test

**Comment by danielkocsis** [comment]
ci:test

**Comment by ealonso** [comment]
Hey @brianchiu @kyle-miho,

Could you please take a look at it? this is a top priority for us and we need to merge it as soon as possible.

It is an important feature for us, to allow users to have a draft version when we are creating a page.

Thanks!!
Eudaldo.

**Comment by danielkocsis** [comment]
Hi @brianchiu,

the CI run has just finished. I would like to highlight that the unique failures are again ones that probably failed because of a CI infra issue. We suffered from these "random" errors during the past few weeks and it makes really hard to figure the real problems out.

Could you guys please take a look on that?

thanks,
Daniel

**Comment by brianchiu** [comment]
Ok. I'm looking!

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Many failures were happening because of issues that are fixed by these two pulls:
1) https://github.com/brianchandotcom/liferay-portal/pull/68639
2) https://github.com/brianchandotcom/liferay-portal/pull/68612

Going to re-run the tests.

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
Alright. This pull looks good. All of the CI tests have unrelated failures, and I've also done a manual check on content pages (and in staging). I'm going to forward this to BChan.

**Comment by brianchiu** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/68647

**Pull request closed without merging**
