### PR TITLE
master-qa-19394

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-19394

### CODE REVIEW

**Comment by brianchiu** [comment]
@kmaria 
Judging by the failure that you put on this ticket - https://issues.liferay.com/browse/LRQA-19394

It seems like BlogsEntry#viewNoEditLinkPG is missing a variable declaration? If so, that's the way that we should fix it because it's more precise than assertTextPresent.

```
<var name="key_entryContent" value="${entryContent}" />
```

**Comment by kmaria** [comment]
@brianchiu indeed

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
Nice! Glad it works.

I moved the variable declaration a couple lines down. We try to declare the variables that get used in path files (the key_variables) right before we need to use them so that we would know which locator key they're used in.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33104

**Pull request closed without merging**
