### PR TITLE
LRQA-48831 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-48831

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
PR submitted to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72716
https://github.com/brianchandotcom/liferay-portal-ee/pull/24304

**Pull request closed without merging**
