### PR TITLE
LPS-87756 Adapt import/export to handle type of fragments

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @brianchiu, @kyle-miho, we now allow the user to add two types of fragments (sections and elements), so this will probably break a lot of tests.....this PR handles also staging and export/import. If you export a collection, you'll see a new property for type. Previous zips of collections are compatible with this

cc:// @ealonso

**Comment by brianchiu** [comment]
@jkappler I'm looking this over now.

We have quite a few failures in ci test relevant right now that are unrelated to this pull.

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/65431

**Pull request closed without merging**
