### PR TITLE
LRQA-44034 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-44034

7.1.x: https://github.com/brianchiu/liferay-portal-ee/pull/4468

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64721
https://github.com/brianchandotcom/liferay-portal-ee/pull/22237

**Pull request closed without merging**
