### PR TITLE
master-en-133

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-16320

### CODE REVIEW

**Comment by evannagayama** [comment]
@brianchiu,

I wasn't sure about this one:
<execute function="Select" locator1="PGKaleoformsSubmitnew#NEW_PROCESS_LINK_TO_PAGE_SELECT" value1="regexp:�C\s+${kfProcessFieldData}" />

**Comment by brianchiu** [comment]
@evannagayama @vicnate5

Can you take a look at this, Victor?

Reference ticket: https://issues.liferay.com/browse/LRQA-7342

**Comment by vicnate5** [comment]
@evannagayama @vicnate5 @GinsonRen The original regexp is correct in KaleoFormsPortlet.macro (line 150). Not sure why the validator changed it.

**Comment by brianchiu** [comment]
@evannagayama @GinsonRen @vicnate5

Based on this ticket: https://issues.liferay.com/browse/LRQA-7342 and also on Victor's comments, I'm going to change that one back to what it was before.

Ginson, can you find out why the validator changed it? We need it to be what it was before, otherwise it won't work.

**Comment by brianchiu** [comment]
@evannagayama @GinsonRen 

I changed the regex to match the one from DDLRecord#populateFieldLinkToPage.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27533
https://github.com/brianchandotcom/liferay-portal-ee/pull/10459
https://github.com/brianchandotcom/liferay-portal-ee/pull/10460

**Comment by GinsonRen** [comment]
@brianchiu @vicnate5 Maybe there is something wrong on the validator, I will talk with Terry and Greg later. Sorry for all the inconvenient.

**Pull request closed without merging**
