### PR TITLE
master-qa-19748

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-19748

### CODE REVIEW

**Comment by brianchiu** [comment]
@kmaria 

@sharonchoi let me know that this is due to a bug where images don't show up if the column the portlet is in is too narrow.

They've submitted a fix here that should take care of your issue. https://issues.liferay.com/browse/LRQA-19636

I'll leave this pull request open for now. Let me know if your tests still fail.

**Comment by brianchiu** [comment]
@kmaria Do you still need this?

**Comment by kmaria** [comment]
@brianchiu yes, test is still failing

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
I think DM has changed a little bit? The same test failed twice. I'll retest it one more time to be sure.

**Comment by brianchiu** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32916

**Pull request closed without merging**
