### PR TITLE
LPS-92553 Rename method since the separator can be for other contributors that are not assets

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:wem-msb

**Comment by jkappler** [comment]
@brianchiu, @kyle-miho, we changed to use info display contributor instead of asset display contributor for asset display pages (which will be known as display pages) and for standard pages. So I prefer to send you the PR first. The field mapping should still work since it's backwards compatible. Please let me know what you think please.

Thanks

cc:// @ealonso

**Comment by jkappler** [comment]
cc:// @jorgeferrer

**Comment by brianchiu** [comment]
@jkappler thanks. I'm taking a look.

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
Results here:
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=506467712

**Comment by brianchiu** [comment]
All the results are good. Those failures are present in upstream / unrelated.

**Comment by brianchiu** [comment]
PR sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70195

**Pull request closed without merging**
