### PR TITLE
master-qa-15518

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-15518

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama 
How does this fix the issue? Page#gotoPG will run "openURL" at the beginning.

**Comment by evannagayama** [comment]
When the openURL navigates to the same site and page, it doesn't navigate to the "home" of the dm portlet. But with the new openURL it navigates to the Liferay site then back to the other site where the dm portlet is back to the "home". Let me know if you want to see it.

**Comment by brianchiu** [comment]
Thanks Evan. I don't need to see it. Doesn't sound ideal though. We should fix it.

I create new openURL macros in Navigation.macro. You should see if any of those fit what you need.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26381

**Pull request closed without merging**
