### PR TITLE
LPS-91520 Buildlang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:wem-msb

**Comment by pavel-savinov** [comment]
Hi @brianchiu, this pull breaks some navigation menus tests for sure. Could you please take a look?

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
PR sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69005

**Pull request closed without merging**
