### PR TITLE
master-qa-23292

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-23292

### CODE REVIEW

**Comment by brianchiu** [comment]
@kmaria 
In this case, is it possible to just use "Check#checkToggleSwitch" instead of creating a new function?

If not, can "Check#toggleSwitch" just use "AssertElementPresent" instead of having to create a new "AssertChecked#checkedToggleSwitch", since "AssertChecked#checkedToggleSwitch" pretty much does the same thing as AssertElementPresent?

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
@brianchiu added AssertElementPresent as you suggested :)

**Comment by brianchiu** [comment]
Sounds good

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37947

**Pull request closed without merging**
