### PR TITLE
LPS-91641 Avoid NullPointerException

### PR DESCRIPTION
**Pull request by ealonso**
Hey @brianchiu @kyle-miho,

We replace the radio button with a select when you are selecting a display page, see the following screenshot:

la_vida_se_abre_paso_en_el_ecosistema_radiactivo_de_chernobil_-_liferay

Could you please update the tests?

Thanks!!

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@ealonso Thanks for sending this. I like this change!

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
@ealonso I am sending this to BChan. I found one thing:

When mousing over the input field, the is an untranslated key.

default-display-page-name-input

specific-display-page-name-input

PR sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69206

**Pull request closed without merging**
