### PR TITLE
LPS-92312 Use source/target naming to make it consistent. If a draft layout exists, copy to it, otherwise directly to the target layout (mostly if it's not a standard page)

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
Pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69822

I tested the bug and it passes. Otherwise, the test failures look unrelated.

**Pull request closed without merging**
