### PR TITLE
LPS-90446 Write portlet paths for all portlets inside fragment entry link

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchiu, I prefer to send this to you first, just in case it breaks sth. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:msb

**Comment by jkappler** [comment]
@dacousalr, we will probably need to do a backport of this to 7.1. Will keep you posted

cc:// @ealonso, @kyle-miho

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
@jkappler 
The pull looks good (from a frontend test perspective). The existing failures are unrelated to this pull.

However, the very first time you add the docs and med widget it will still have it. Once you switch to view mode it goes away. Can you take a look?

**Pull request closed without merging**
