### PR TITLE
LPS-94910 Adds missing dependency

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchiu** [comment]
@jkappler Is this something to be fixed in this pull?
```
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:fragment:fragment-api:baseline'.
     [exec] > Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.fragment.api-3.0.0.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.fragment.api/2.3.0/86e6477fe1b06933981175d4e193c040e3a711ac/com.liferay.fragment.api-2.3.0.jar
```

**Comment by brianchiu** [comment]
fyi running baseline did not work for me.
```
* What went wrong:
Could not resolve all files for configuration ':apps:frontend-js:frontend-js-loader-modules-extender-api:compileClasspath'.
> Could not find com.liferay.portal:com.liferay.portal.kernel:5.0.0-SNAPSHOT.
  Searched in the following locations:
    - file:/L:/ce/master/.m2/com/liferay/portal/com.liferay.portal.kernel/5.0.0-SNAPSHOT/maven-metadata.xml
    - file:/L:/ce/master/.m2/com/liferay/portal/com.liferay.portal.kernel/5.0.0-SNAPSHOT/com.liferay.portal.kernel-5.0.0-SNAPSHOT.pom
    - file:/L:/ce/master/.m2/com/liferay/portal/com.liferay.portal.kernel/5.0.0-SNAPSHOT/com.liferay.portal.kernel-5.0.0-SNAPSHOT.jar
    - https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.portal.kernel/5.0.0-SNAPSHOT/maven-metadata.xml
    - https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.portal.kernel/5.0.0-SNAPSHOT/com.liferay.portal.kernel-5.0.0-SNAPSHOT.pom
    - https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.portal.kernel/5.0.0-SNAPSHOT/com.liferay.portal.kernel-5.0.0-SNAPSHOT.jar
  Required by:
      project :apps:frontend-js:frontend-js-loader-modules-extender-api
```

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:close

**Comment by pavel-savinov** [comment]
Resent here https://github.com/brianchiu/liferay-portal/pull/1919

**Pull request closed without merging**
