### PR TITLE
LPS-90965 Adjust styles

### PR DESCRIPTION
**Pull request by ealonso**
Hey @brianchiu @kyle-miho,

As part of https://issues.liferay.com/browse/LPS-89112, we've moved the buttons to a toolbar in the top.

new_web_content_-_liferay

Could you please take a look at it? 

Thanks!

Eudaldo.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
I can't reproduce the test failures and they seem unrelated too.

**Comment by brianchiu** [comment]
PR sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69002

**Pull request closed without merging**
