### PR TITLE
master-qa-25556

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-25556

### CODE REVIEW

**Comment by brianchiu** [comment]
@kmaria 
Would using the regular "publishToLive" macro work in this case? Is it necessary to have this different one?

I also renamed it because our macros should follow the verbNoun format.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40355

**Comment by kmaria** [comment]
@brianchiu no, wouldn't work, 'cause publishToLive works on page. At global we don't have page, publishing can be reached via Staging menu item only.
Thanks for renaming.

**Comment by brianchiu** [comment]
@kmaria 
Got it. Thanks for the explanation.

**Pull request closed without merging**
