### PR TITLE
LRQA-41273 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-41273

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@brianchiu looks like the new way to add/import collections for fragment collections got through? Even though they caused these functional test failures. (Actually its probably because they've been failing due to the Blank Site issue)

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/59340

**Pull request closed without merging**
