### PR TITLE
master-qa-19213

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-19213

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama

SitelocalizationUsecase#NoLocalePrependedWhenLocaleMatchMyPreferredLocalization

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianwulbern 
Let me talk to you about this one tomorrow.

```
<tr>
	<td>EMAIL_ADDRESS</td>
	<td>//div[label[contains(@for,'login')]]/input[@type='text']</td>
	<td></td>
</tr>
```

If it's something like this, it isn't generic anymore and doesn't necessarily belong in TextInput.path.

**Comment by brianwulbern** [comment]
One alternative I'm thinking would be to pipe the Spanish translation of the field labels into the locator, like this:

```
<tr>
    <td>EMAIL_ADDRESS</td>
    <td>//button[contains(.,'Email Address')] | //button[contains(.,'Dirección de correo ')]</td>
    <td></td>
</tr>
... 
<tr>
    <td>PASSWORD</td>
    <td>//div[label[contains(.,'Password')]]/input | //div[label[contains(.,'Contraseña')]]/input</td>
    <td></td>
</tr>
```

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31915

**Pull request closed without merging**
