### PR TITLE
master-bw-22

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-17407

### CODE REVIEW

**Comment by brianwulbern** [comment]
@brianchiu 

This fix doesn't need to be backported to 7.0.x.  Thanks.

**Comment by brianchiu** [comment]
@brianwulbern @anthony-chu 
I've gotten confirmation from Anthony that this won't break any of our tests. Since it won't break anything, I'll still request a backport for this.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@anthony-chu @brianwulbern 
If the ci retest fails again, please look into this.

**Comment by brianchiu** [comment]
Fails CI so not merging for now.

**Comment by brianchiu** [comment]
This was resent in:
https://github.com/brianchiu/liferay-portal/pull/623

**Pull request closed without merging**
