### PR TITLE
LPS-89474 bnd.bnd

### PR DESCRIPTION
**Pull request by brianchiu**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
ci:test:relevant:norebase

**Comment by brianchiu** [comment]
Pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/67573

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
