### PR TITLE
LPS-90281 Buildlang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianchiu @kyle-miho,

We've moved some inputs fields in the web content form:

1. We add a new panel called "Basic Info"
- We've moved **description** to that panel
- We've moved **version info** to that panel
- We've moved **article Id** to that panel. This appears if you enable the auto ID
 
2. Update friendly url info
3. Removes the possibility of change structure or edit the structure, also we add the information of the selected structure on the "Basic Info" panel

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:bundle:norebase

**Comment by brianchiu** [comment]
ci:test:relevant:norebase

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@kyle-miho Can you take a look at this one?

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
ci:test:bundle

**Comment by kyle-miho** [comment]
ci:close

**Pull request closed without merging**
