### PR TITLE
LRQA-29681, LRQA-29679 | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LRQA-29681
https://issues.liferay.com/browse/LRQA-29679

### CODE REVIEW

**Comment by nikki-pru** [comment]
From https://github.com/sharonchoi/liferay-portal/pull/1007 

Commits for 7.0.x sent in PR #1547 

@brianwulbern, please see changes.

**Comment by brianwulbern** [comment]
@liuxingye see changes

**Comment by liuxingye** [comment]
@brianwulbern  got it, thanks

**Comment by brianchiu** [comment]
@nikki-pru 
I changed the way you passed in the key_variable so it's more clear where it's being used.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45555
https://github.com/brianchandotcom/liferay-portal/pull/45556

**Pull request closed without merging**
