### PR TITLE
master-qa-14389

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-14389

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama 

Can you send me a pull for ee-6.2.x as well with just the dependencies and properties?

**Comment by evannagayama** [comment]
Pushed to 6.2 branches:
https://github.com/brianchiu/liferay-portal-ee/pull/3800
https://github.com/brianchiu/liferay-portal-ee/pull/3801

**Comment by brianchiu** [comment]
SF for ENagayama.

@evannagayama 
Changed "Xsl" to "XSL".

Fixed your spelling error on "dependencies" commit message.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26257
https://github.com/brianchandotcom/liferay-portal-ee/pull/9903
https://github.com/brianchandotcom/liferay-portal-ee/pull/9904
https://github.com/brianchandotcom/liferay-portal-ee/pull/9905
https://github.com/brianchandotcom/liferay-portal-ee/pull/9906

**Pull request closed without merging**
