### PR TITLE
master-sc-22

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-12981

### CODE REVIEW

**Comment by sharonchoi** [comment]
@brianchiu turning off test in master, because of blogs portlet

**Comment by brianchiu** [comment]
@sharonchoi 

I'm changing your "SF" commit to say "Turn off tests".

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal-ee/pull/9592
https://github.com/brianchandotcom/liferay-portal-ee/pull/9591
https://github.com/brianchandotcom/liferay-portal/pull/25502

**Pull request closed without merging**
