### PR TITLE
LPS-90755 Moves code to creation menu

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Hey @ealonso 
There are a couple of little strange things.
1) When assigning users, the default view is Card view, but the icon in the upper right says it's Table view.


2) When assigning user groups, it says "Assign New User" when it should say "Assign New User Group". Also, even though I created a user group, it does not show up... but I need to look into that more because I think that is outside of this pull.

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/68287

**Pull request closed without merging**
