### PR TITLE
master-qa-15236

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-15236

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5 
Is this a real failure?

**Comment by brianchiu** [comment]
ci:retest

**Comment by vicnate5** [comment]
The failure does not look related to my changes

**Comment by brianchiu** [comment]
SF for VWare.

@vicnate5 
I added a couple line breaks.

For the var method ones, even though traditionally we've kept them together, we should stick to the rules we have, so if the order in which those commands is executed matter, then we keep them separate.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34119

**Pull request closed without merging**
