### PR TITLE
master-sc-93

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-9500

### CODE REVIEW

**Comment by brianchiu** [comment]
@sharonchoi @austinchiang 
Do those CK editor path changes work for everything?

Also, WikiEntry.macro needs to be alphabetized.

**Comment by austinchiang** [comment]
@brianchiu @sharonchoi  Yes, the path changes for CK editor work. I've confirmed this with Message Boards and WCM.

**Comment by brianchiu** [comment]
SF for AChiang / SChoi.

@sharonchoi @austinchiang 
I sorted the WikiEntry.macro.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29382

**Pull request closed without merging**
