### PR TITLE
master-qa-19530

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-19530

### CODE REVIEW

**Comment by brianchiu** [comment]
@kenjiheigel 
Can you rebase this tomorrow? It conflicted with a couple other things that I had to push.

**Comment by kenjiheigel** [comment]
@brianchiu, fixed the rebase errors and updated this branch.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32602

**Pull request closed without merging**
