### PR TITLE
LPS-85305 Adds search container id and allow selection

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianchiu,

We think that we are going to broke some poshi tests, Could you please take a look at it?

cc: @jkappler

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
I wasn't able to locally reproduce that functional test failure. I'm going to send this to BChan and we'll monitor whether there are other failures.

https://github.com/brianchandotcom/liferay-portal/pull/63446

**Pull request closed without merging**
