### PR TITLE
LPS-80625 Customize success message

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Also we are checking file extensions, we only accept zip files

**Comment by brianchiu** [comment]
@ealonso Got it. Thanks!

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@ealonso I messaged you on slack about this.

**Comment by ealonso** [comment]
Hey guys,

I fixed the problem with absolute path and sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/59998

**Pull request closed without merging**
