### PR TITLE
LRQA-16341

### PR DESCRIPTION
**Pull request by matethurzo**
hey @brianchiu 

I've applied the contains pattern to those paths where we can be sure it's not ambiguous. So for example in case of the 'description' field I've left it '_200_description' to make sure the test case won't mistake it for other description field.

Let me know if this is ok, or we should do it otherwise.

Thanks,

Máté

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchiu** [comment]
@matethurzo 

Thanks. This looks good. That's what we've been doing as well - we've started removing the portlet id's and switching to use contains so that when the portlet id changes it doesn't break everything.

I have a SF commit where I've removed the extra space between the comma and quote in the identifiers so that they'll be consistent with our other identifiers.

Example:
```
//button[contains(@id, '_addButton')]
```
Changed to:
```
//button[contains(@id,'_addButton')]
```

**Comment by matethurzo** [comment]
Thanks, I'll keep that SF rule in mind :)

There was on other thing I wasn't sure of: '_addButton' or 'addButton' without the underscore? I could see examples for both in the code.

**Comment by brianchiu** [comment]
@matethurzo 

Either one is fine. We haven't set a rule for that. We've always left what's used in the contains statement up to the test writer's judgment.

**Comment by matethurzo** [comment]
got it. thanks!

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27790

**Comment by brianchiu** [comment]
@matethurzo 

Sorry, I edited my last comment a little bit with more info. I didn't expect you to read it so quickly =).

**Comment by matethurzo** [comment]
:)) I've read the edited one as well! Thanks again!

**Pull request closed without merging**
