### PR TITLE
master-ac-32

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-27160

**This is a master-only test.**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Changed the commit message to be under LPS-67072.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/43182

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/43238

**Pull request closed without merging**
