### PR TITLE
LPS-91286 Fix integration test

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@pavel-savinov I'm sorry. This error has affected both of the ci test relevant runs. I'm running it again but I'll be off before the results come back.
```
Could not resolve module: com.liferay.fragment.web
```

**Comment by liulukiwi** [comment]
Brian Chiu hands off this work to me. I'm looking into the unique failures in the new relevant run.

**Comment by liulukiwi** [comment]
Hi @brianchiu , no Could not resolve module error in the new run and create LPS-91606 for case LocalFile.WidgetPagesUseCase#SitesPrivatePagesPermissions.

**Comment by brianchiu** [comment]
Resent here:
https://github.com/brianchiu/liferay-portal/pull/1804

**Pull request closed without merging**
