### PR TITLE
master-qa-16054

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-16054

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchiu this is the second part of LRQA-16054 which includes changes to the Solr Poshi test.

**Comment by brianchiu** [comment]
@alee8888 

Can you fix this? It's a build-selenium error.

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
@brianchiu Closing this PR for now as "#" is still an issue even at the macro level. Testing at the path level.

**Pull request closed without merging**
