### PR TITLE
LPS-90273 Use correct icons for the sections and move widgets to the correct position

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
Pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68436

**Pull request closed without merging**
