### PR TITLE
TESTING..master-qa-19006

### PR DESCRIPTION
**Pull request by lawrence-lee**
https://issues.liferay.com/browse/LRQA-19006 
Don't push this yet. I just wanted to test this

### CODE REVIEW

**Comment by brianchiu** [comment]
@lawrence-lee 
Ok. Not pushing this yet.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@brianchiu 
Looks like the property attribute got declared twice here: https://github.com/lawrence-lee/liferay-portal/commit/22e2471819acae321ca2e6c2193afa2e309207d6#diff-8fa0b0752fa4015823b463e7382b6b5bR199

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31705

**Pull request closed without merging**
