### PR TITLE
master-bw-117

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-19151

### CODE REVIEW

**Comment by brianwulbern** [comment]
@brianchiu @vicnate5

This will change the landing spot when dragging fields.  I initially didn't want to change something used by so many tests, but the change is pretty ingenious: just drag the field _to_ the middle of the area where you can drag the fields _from_.  It's how I add fields manually, and the test works for me locally.

**Comment by brianwulbern** [comment]
@evannagayama

Reviewing Jason's work (which is also WCM's, at the moment :).

**Comment by vicnate5** [comment]
:thumbsup:

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31915

**Pull request closed without merging**
