### PR TITLE
master-en-137

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-16320

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama @brianwulbern 

Does this need to be in ee-6.2.x/ee-6.2.10 too?

**Comment by brianchiu** [comment]
@evannagayama @brianwulbern 

I'll wait on the other two pulls before getting to this one.

**Comment by evannagayama** [comment]
@brianchiu 

I cherry-picked and pushed the other 2 here:
https://github.com/brianchiu/liferay-portal-ee/pull/4051
https://github.com/brianchiu/liferay-portal-ee/pull/4052

**Comment by brianchiu** [comment]
Alright, I'll merge this in.

@vicnate5 @brianwulbern 
Can you guys check the tests on Monday to make sure they still work with this?

@brianwulbern 
Can you comment on the ticket explaining why it was reopened?

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27578
https://github.com/brianchandotcom/liferay-portal-ee/pull/10477
https://github.com/brianchandotcom/liferay-portal-ee/pull/10478

**Comment by brianwulbern** [comment]
@brianchiu, Done. Left a comment on the ticket for why it was reopened.

https://issues.liferay.com/browse/LRQA-16320

**Pull request closed without merging**
