### PR TITLE
LPS-85831 No needed

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianchiu, @kyle-miho

We update the edit for content pages, now we have an edit mode directly on the pages. You have more information about he story here: https://issues.liferay.com/browse/LPS-81870

Could you please take a look at it and fix possible test failures?

Thanks!!
Eudaldo.

**Comment by brianchiu** [comment]
Fixed tests and sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/63630

**Comment by brianchiu** [comment]
@ealonso 
There are some minor things. I'll message you about it on slack.

**Comment by brianchiu** [comment]
For my own reference as issues to track:
1. The success message is missing after adding a content page
2. The fragment add panel defaults to closed (it used to default to open). I also couldn't immediately figure out that the plus icon was meant for expanding that panel (maybe I'm a little too used to seeing that for adding widgets)
3. The first time you open the fragment add panel, some of the padding is messed up. It fixes itself later on
4. In "edit mode" the icon is a cog, but there's already another cog icon, so that might be confusing for people.
5. We'll need to add tooltips / help text when hovering over

**Pull request closed without merging**
