### PR TITLE
LPS-89176 Add column in upgrade process

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
he @brianchiu, @kyle-miho, I'm unsure if this breaks tests, so I prefer to send it to you first

Please let me know if it's okay

Thanks!

**Comment by brianchiu** [comment]
@jkappler thanks! Taking a look

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@jkappler 
There seems to be some sort of javascript error on master portal startup in the upgrades tests (immediately after upgrade). Those failures are not happening elsewhere.
```
ReferenceError: AUI is not defined [http://localhost:8080/o/classic-theme/js/main.js?browserId=firefox&minifierType=js&languageId=en_US&b=7200&t=1547760114972:2]
```
This screenshot is from upgrading from 7.0.4 to master.

after

Let me know if you need me to help you with anything else for this or if you need help reproducing it.

**Pull request closed without merging**
