### PR TITLE
master-qa-18286

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-18286

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Mistakenly made this an acceptance test. Updating the pull..

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/30701

**Pull request closed without merging**
