### PR TITLE
master-rs-44

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-26853

### CODE REVIEW

**Comment by brianchiu** [comment]
Hey @GinsonRen @Sharryxue @xbrianlee

Is this needed for 7.0.x?

Based on the ticket: https://issues.liferay.com/browse/LRQA-26853, 
This test fix is caused by https://issues.liferay.com/browse/LPS-67289. So we'll only need this commit in 7.0 if LPS-67289 gets backported?

**Comment by Sharryxue** [comment]
Hello @brianchiu @GinsonRen
Yes, the related case can be passed on 7.0.x head now. The commit in [LRQA-26853](https://issues.liferay.com/browse/LRQA-26853) should be packported after [LPS-67289 ](https://issues.liferay.com/browse/LPS-67289) .

**Comment by brianchiu** [comment]
Alright. Since this commit should be backported only if LPS-67289 gets backported too, I'm going to change the commit message to say LPS-67289. That way, support will know to include this commit if they decide to backport.

See: https://loop.liferay.com/home/-/loop/feed/2212959

**Comment by brianchiu** [comment]
CC @brianwulbern

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42156

**Comment by brianwulbern** [comment]
Thanks, BChiu.

**Pull request closed without merging**
