### PR TITLE
 LRQA-49143 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-49143

cc @brianwulbern @GinsonRen

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
forsh-poshed for source format issue

**Comment by brianchiu** [comment]
@liulukiwi Thank you!

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74055
https://github.com/brianchandotcom/liferay-portal-ee/pull/24821

**Pull request closed without merging**
