### PR TITLE
master-kg-3

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-16984

### CODE REVIEW

**Comment by koor4356** [comment]
No changes.

**Comment by brianchiu** [comment]
@koor4356 @anthony-chu 

Does it have to use "Click#clickAt"? Will just a normal "Click" work?

**Comment by anthony-chu** [comment]
@brianchiu I tested with just a normal "Click" and POSHI was unable to interact with the Dockbar element. Using "Click#clickAt" allowed POSHI to properly click the element.

**Comment by brianchiu** [comment]
ok. Thanks.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/28589

**Pull request closed without merging**
