### PR TITLE
LRQA-36007 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-36007

@brianchiu, not sure if these tests weren't running on purpose, so I sent the master pull to you first.  I'll send 7.0 to BChan.

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@brianchiu do you know if these tests weren't running for some reason?

**Comment by brianchiu** [comment]
@brianwulbern 
I'm not sure why. I can see why we would leave it out of the PR tester, but I don't know why we don't run them at all.

Either way, I checked in with Albert, and he said we should be running these.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchiu/liferay-portal/pull/1609#issuecomment-343831303

**Pull request closed without merging**
