### PR TITLE
master-qa-24286

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-24286 172f49d is the actual fix to be committed to master, all others are if you want to run on FF45

### CODE REVIEW

**Comment by jpince** [comment]
@brianchiu Also note that 101fb85 will have a merge conflict with master. If you're good with this change, I'll make a new ticket to find a better way to wait for something in the html... as of right now, doesn't look like anything changes when the portlet topper becomes visible.

**Comment by brianchiu** [comment]
@jpince 
kk. I'll just pull in the make visible change first.

**Comment by brianchiu** [comment]
@jpince 
I reworded the commit message so that it gives more context/clarity as to why we're making the change.

"LRQA-24286 Give time in makeVisibleClickAt for elements to expand into view after mouse over"

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/39284

**Pull request closed without merging**
