### PR TITLE
master-jz-26

### PR DESCRIPTION
**Pull request by jaredzimmerman1**
https://issues.liferay.com/browse/LRQA-14939

### CODE REVIEW

**Comment by brianchiu** [comment]
@jaredzimmerman1 @vicnate5 

Why is the viewMonth macro command written like this? If it's not February click the previous button, but anything else it'll keep clicking the next button?

```
	<command name="viewMonth">
		<execute macro="CalendarEvent#changeViewPG">
			<var name="viewType" value="Month" />
		</execute>

		<while>
			<condition function="IsTextNotEqual" locator1="PGCalendar#SCHEDULER_VIEW_MONTH_DATE" value1="February 2015" />
			<then>
				<execute function="Click" locator1="PGCalendar#VIEW_PREVIOUS_BUTTON" />
			</then>
		</while>

		<while>
			<condition function="IsTextNotEqual" locator1="PGCalendar#SCHEDULER_VIEW_MONTH_DATE" value1="${dateMonth}" />
			<then>
				<execute function="Click" locator1="PGCalendar#VIEW_NEXT_BUTTON" />
			</then>
		</while>
	</command>
```

**Comment by jaredzimmerman1** [comment]
@brianchiu,

So this is what will happen:

- The test will always use the current month when it starts running, so there will never be a situation where the test starts before Feb 2015 and therefore clicks "Previous" indefinitely.
- The test will click "Previous" until it reaches Feb 2015, our baseline.
- Then it will click "Next" until it reaches the month we need.

It's the best way to get the calendar to select the month we need without much more complicated logic.

**Comment by brianchiu** [comment]
@jaredzimmerman1 

Thanks. Makes sense. I'm going to add a comment in the macro

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25758

**Pull request closed without merging**
