### PR TITLE
master-qa-24541

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-24541

cc @brianwulbern

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@kmaria 

:+1: 

One question, in your commit `LRQA-24541 Remove descriptive view from test`, are you removing the _List_ view option because it's set that way be default?

c.f. (https://github.com/brianchiu/liferay-portal/pull/1322/commits/12217fb541d916964ef2dd93f855f55a27e3d889#diff-9911263236ac55cc136cd13a4fa2c092L965)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38896

**Comment by kmaria** [comment]
@brianwulbern no, I'm removing it because the assert path is valid for the default Descriptive view.

**Comment by brianwulbern** [comment]
@kmaria Ah, makes sense.  Thanks!

**Pull request closed without merging**
