### PR TITLE
LPS-90634 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-90634

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
@brianchiu you can close story after this gets pushed

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68160

**Pull request closed without merging**
