### PR TITLE
LPS-81405 buildlang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianchiu @kyle-miho,

It's possible that some tests are broken with my changes, I've update the name of layout -> widget page and content -> content page.

Please see the image as result of my changes: 
select_template_-_liferay

Thanks!!
Eudaldo.

**Comment by brianchiu** [comment]
@ealonso Thanks! We'll get on this right away.

**Comment by brianchiu** [comment]
I fixed a typo -> "in line" should be "inline".

Testing it here:
https://github.com/brianchiu/liferay-portal/pull/1630

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/59028

**Pull request closed without merging**
