### PR TITLE
master-qa-18993

### PR DESCRIPTION
**Pull request by lawrence-lee**
https://issues.liferay.com/browse/LRQA-18993

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@lawrence-lee, @kiyoshilee says it's going to break again, and they're aware of it. They said they'll fix it later, so triggering additional tests won't help.

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31652

**Pull request closed without merging**
