### PR TITLE
master-ml-158

### PR DESCRIPTION
**Pull request by mandyzia**
https://issues.liferay.com/browse/LRQA-14903

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@mandyzia @christianstokes 

I'm going to send the first commit to BChan first.

Also,
@christianstokes 

```
		<var name="key_serverPropertyName" value="appsrv.name" />
```
Where does appsrv.name get passed in?

**Comment by christianstokes** [comment]
@mandyzia @brianchiu 

Hi Brian,

"appsrv.name" is a text string found in the LCS Portal. It has nothing to do with ANT or POSHI. It's just the name of a table that is being viewed in our test. See attached screenshot:

appsrv

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal-ee/pull/9660
https://github.com/brianchandotcom/liferay-portal-ee/pull/9659
https://github.com/brianchandotcom/liferay-portal-ee/pull/9658
https://github.com/brianchandotcom/liferay-portal-ee/pull/9657
https://github.com/brianchandotcom/liferay-portal/pull/25671

**Pull request closed without merging**
