### PR TITLE
Remove conditionals (Iteration #3)

### PR DESCRIPTION
**Pull request by brianchiu**
test

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
@kenjiheigel

**Comment by brianchiu** [comment]
ci:stop

**Comment by sharonchoi** [comment]
ci:retest:gauntlet

**Comment by brianchiu** [comment]
New pull here:
https://github.com/brianchiu/liferay-portal/pull/1588

**Pull request closed without merging**
