### PR TITLE
master-qa-21049

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-21049

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama
Can you review this? I don't know how it affects your tests. If it's good to go, send it to BChan.

**Comment by evannagayama** [comment]
Hi Maria, BChiu asked me to look at this pr because it has web content changes. As I was looking into it I believe that the changes you made were not necessary because the macros already exist. Sorry we had changed it and these changes have affected your test.

1. WebContentTemplates#addCP does not need the if block to be added. The template is meant to be created with 3 macros, for example here:
		<execute macro="WebContentTemplates#addCP">
			<var name="templateDescription" value="WC Template Description" />
			<var name="templateName" value="WC Template Name" />
		</execute>

		<execute macro="WebContentTemplates#addStructure">
			<var name="structureName" value="WC Structure Name" />
			<var name="templateFieldNames" value="Text" />
		</execute>

		<execute macro="WebContentTemplates#save" />
2. WebContent#addWithStructureCP is only supposed to fill in the fields that were created by the Structure. Therefore the added block <execute macro="WebContent#selectTemplateCP" /> should not be added here. By fixing the first part I believe this one will not be necessary.

Sorry, I know this is kind of confusing. In summary, we made changes to wc that affected your tests. Because of these changes the macro functionality already exists, but need to be updated in your tests. Sorry for the inconvenience, we are trying to make our macros better! Please let me know if you have any question about this.

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34625

**Comment by brianchiu** [comment]
Thanks, @evannagayama

**Pull request closed without merging**
