### PR TITLE
master-vw-21

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-17941

Hey @brianchiu, I need to send this to @rafaprax so that the PR tester passes, but I wanted to run it by you first because I made a few changes to the teardown. The DDL fix for Lexicon still needs some additional work but I want to wait until https://issues.liferay.com/browse/LPS-58581 is actually at head. If you want to just close this after your review I can forward it on, or you can send it to @rafaprax yourself.

@marcellustavares in the future can we wait until changes are past your review and ready for BChan before we fix the tests? That would be a lot easier on my end.

### CODE REVIEW

**Comment by marcellustavares** [comment]
sure we'll do that next time! thx @vicnate5

**Comment by brianchiu** [comment]
@vicnate5 
I'll look at this now.

**Comment by brianchiu** [comment]
@vicnate5 
Poshi part looks fine. Go ahead and send this to Rafael.

**Comment by vicnate5** [comment]
Pushed to Rafael:
https://github.com/rafaprax/liferay-portal/pull/29

**Pull request closed without merging**
