### PR TITLE
master-qa-19815

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-19815

### CODE REVIEW

**Comment by brianchiu** [comment]
@kmaria 
Can you rebase this and resend?

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
Sorry. I'll get to this tomorrow. There are a few things I want to change, but I don't have time to get to it before today.

**Comment by brianchiu** [comment]
@evannagayama 
Can you take this in and push it? 

Some changes I'd want is to make the macros that @kmaria more parallel to the current ones in the product menu macros.

I'm trying to fix my repository right now. I think some files that were either too long or have weird characters in the names got in and windows is complaining. BChan fixed it here: https://github.com/liferay/liferay-portal/commit/3a27db157e07ec93b1cbaa47f162e36c3e39d596. But I can't get my repo working yet.

**Comment by evannagayama** [comment]
SF For @kmaria.
1. Removed the 2 paths you created because they already existed. One of them I renamed to be better.
2. Added "<execute macro="ProductMenuHelper#openProductMenu" />" in both the macros because they make sure the product menu is open before performing actions.

**Comment by evannagayama** [comment]
@brianchiu no problem.
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32964

**Comment by brianchiu** [comment]
@evannagayama 
Thanks, man.

**Pull request closed without merging**
