### PR TITLE
master-qa-15307

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-15307

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama 

Can you resend with "Rss" renamed to "RSS"? It should be all caps.

**Comment by evannagayama** [comment]
@brianchiu I've updated the pr. Once this is pushed in I'll fix the location of the RSS testcase, macro, and path.

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
@evannagayama 
Send the dependencies/properties commit for 6.2 and 6.1 also.

**Comment by evannagayama** [comment]
Completed:
https://github.com/brianchiu/liferay-portal-ee/pull/3829
https://github.com/brianchiu/liferay-portal-ee/pull/3830

**Comment by brianchiu** [comment]
SF for ENagayama.

@evannagayama 
We don't need the BaseLiferay.action changes because we don't use the actions files anymore.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26430
https://github.com/brianchandotcom/liferay-portal-ee/pull/9960
https://github.com/brianchandotcom/liferay-portal-ee/pull/9961
https://github.com/brianchandotcom/liferay-portal-ee/pull/9962
https://github.com/brianchandotcom/liferay-portal-ee/pull/9963

**Pull request closed without merging**
