### PR TITLE
master-qa-16992

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-16992

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchiu, just testing this on poshi runner in the PR tester for now. Once poshi runner is stable on master, we can merge this barring complications.

**Comment by kenjiheigel** [comment]
These changes will break build-selenium. It should work with the poshi runner validation though.

**Comment by kenjiheigel** [comment]
Once this goes in, the PR tester will be updated:
https://issues.liferay.com/browse/LRQA-17682

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29799

**Pull request closed without merging**
