### PR TITLE
master-qa-16054

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-16054

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchiu these changes were needed because of 2 things:
1. We have updated the Solr version from 4.10.3 to 5.2.1 which required different setup.
 * Instead of starting Solr via a jar we are not using the built in Solr scripts to start and create the necessary solr core.
2. Solr4-web plugin has been moved into portal as a module. 
* This requires the Elasticsearch OSGI bundle to be deleted in order to deploy the Solr module.

**Comment by brianchiu** [comment]
@alee8888 
1. Declare solr.server.dir below solr.version
2. deploy-solr-module doesn't need to be its own target

**Comment by alee8888** [comment]
@brianchiu I have updated the commits based on your feedback. Thanks

**Comment by brianchiu** [comment]
@alee8888 
I'll get to this tomorrow morning.

1. Can you squash your sort commit so that adds the delete target is in the correct place? Generally it's not good practice to source format your own changes.
2. delete-elasticseach-osgi-bundle - is there a better name for this? The more I look at it the more it doesn't match deleting a jar.

**Comment by alee8888** [comment]
Resent in: https://github.com/brianchandotcom/liferay-portal/pull/27907

**Pull request closed without merging**
