### PR TITLE
master-en-6

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-14196

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama 

See error above. Please resend.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
SF for Enagayama / BWulbern.

@evannagayama @brianwulbern 
I fixed the source formatting error. See my SF commit.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/24681

**Pull request closed without merging**
