### PR TITLE
LRQA-17648 Updating test cases against menuitem displacement

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Seems like problem of the test environment

**Comment by brianchiu** [comment]
@matethurzo @kmaria 
I'll look into this, but you're right that the failure has nothing to do with Maria's commits.

**Comment by brianchiu** [comment]
ooooo I take back what I said.

This failure happened because there is an extra space after "gotoPublishingtools".

https://github.com/matethurzo/liferay-portal/commit/b0422617f4169f1116b9835434d85f0d591b2168

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29772

**Pull request closed without merging**
