### PR TITLE
master-qa-45274

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-45274

Hello @brianchiu, I've made the test-fix as I explained [here](https://issues.liferay.com/browse/LRQA-45274?focusedCommentId=1723437&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1723437), but I'm not pretty sure if it's OK to make changes like this, so I send the commit to you to review, sorry for any inconvenience. Thanks

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
The related case is passed on ci.
[Sharryxue/liferay-portal#55](https://github.com/Sharryxue/liferay-portal/pull/55)

**Comment by brianchiu** [comment]
Thanks, @Sharryxue. Good job! :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69549

**Pull request closed without merging**
