### PR TITLE
master-qa-16046

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-16046

### CODE REVIEW

**Comment by brianchiu** [comment]
@alee8888 

Rebase error. Please fix.

**Comment by alee8888** [comment]
ci:retest

**Comment by brianchiu** [comment]
SF for ALee.

@alee8888 
1. I split up your test commit into 2 - one that adds the test and one that turns the test off
2. General SF -> when order of executes matter we add extra line break

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/28164

**Pull request closed without merging**
