### PR TITLE
master-qa-17044

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-17044

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchiu The fix looks weird, but that is because we are setting liferay.home to the portal source directory in build.hostname.properties on Jenkins.

This works because when we set app.server.bundle.index to a value other than 0, it will point liferay.home to app.server.parent.dir-1 instead of portal-source.

And sorry for not backporting back down to ee-6.2.10/ee-6.1.x/ee-6.1.30. My repo is still messed up but I will fix this by the next time I submit a PR that requires it to be backported to other branches.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@alee8888 

Let's talk about this tomorrow. I just want to make sure I understand what is going on.

**Comment by brianchiu** [comment]
@alee8888 

Sorted it so that liferay.home variable setting is alphabetized.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/28806
https://github.com/brianchandotcom/liferay-portal-ee/pull/10933
https://github.com/brianchandotcom/liferay-portal-ee/pull/10934
https://github.com/brianchandotcom/liferay-portal-ee/pull/10935
https://github.com/brianchandotcom/liferay-portal-ee/pull/10936

**Pull request closed without merging**
