### PR TITLE
master-qa-20421

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-20421

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5 

For these, should we add an assertion that the calendar shows up? Maybe assert the things that you click on to hide the calendar are present? You had an assertion like that for the macros that hid the calendars.

```
	<command name="showCurrentSiteCalendar">
		<execute function="Click" locator1="Calendar#CURRENT_SITE_CALENDARS_CALENDAR_PRIMARY_COLOR_HIDDEN" />
	</command>

	<command name="showMyCalendarsCalendar">
		<execute function="Click" locator1="Calendar#MY_CALENDARS_CALENDAR_PRIMARY_COLOR_HIDDEN" />
	</command>
```

**Comment by vicnate5** [comment]
@brianchiu The reason for the removal of the assertion in those macros is because of the way the calendar renders the icon. The color shows up as the HTML color code when the page loads (D96666), but upon re-enabling the color icon, the color shows up as RGB in the html. 

Now that I think about it, the fix could be to add a pipe to the locator with the RGB and HTML-color variations.

**Comment by brianchiu** [comment]
@vicnate5 
Pipe sounds good to me.

**Comment by vicnate5** [comment]
Will resend.

**Comment by vicnate5** [comment]
Resent:
https://github.com/brianchiu/liferay-portal/pull/1084

**Pull request closed without merging**
