### PR TITLE
master-qa-17471

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-17471

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama

This will move our simple Page#gotoContentCP calls onto ProductMenu#gotoSitesContent instead.  I've only included Content areas that are in portal on startup (e.g., not including 'Knowledge Base', 'Open Social Gadget', etc.).

**Comment by brianwulbern** [comment]
instead of running a retest on this pull (since ci server 1 is down to 1%), please see the identical pull I used as a test here: https://github.com/brianwulbern/liferay-portal/pull/124

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32576

**Pull request closed without merging**
