### PR TITLE
master-qa-14249

### PR DESCRIPTION
**Pull request by alee8888**
http://issues.liferay.com/browse/LIFERAYQA-14249

### CODE REVIEW

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
@brianchiu 
Sort was due to https://github.com/liferay/liferay-portal/commit/356eef40cd63337e688f7d18288a1bf4ee67421a

**Comment by brianchiu** [comment]
@alee8888 

```
<equals arg1="${database.type}" arg2="hsql" />
<equals arg1="${setup.wizard.enabled}" arg2="true" />
```

Is it always needed if setup.wizard.enabled=true?

Shouldn't we use the following instead?
```
<equals arg1="${setup.wizard.initial.database.type}" arg2="hsql" />
```

**Comment by alee8888** [comment]
@brianchiu 

For that part, it doesn't matter which database the JUnit/integration framework is connecting to. It can be different than the database Poshi is connecting too. All of our tests in the past has had JUnit connect to MySQL without any issues but as we add other databases to the tests, we can change this logic.

**Comment by brianchiu** [comment]
SF for ALee.

@alee8888 
I changed the conditional to use "setup.wizard.initial.database.type" instead because the logic in the 'then' block is only needed when Liferay starts on HSQL.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26647
https://github.com/brianchandotcom/liferay-portal-ee/pull/10058
https://github.com/brianchandotcom/liferay-portal-ee/pull/10059
https://github.com/brianchandotcom/liferay-portal-ee/pull/10060
https://github.com/brianchandotcom/liferay-portal-ee/pull/10061

**Comment by brianchiu** [comment]
@alee8888 

I've closed my pulls to BChan. After thinking about it even more, there's a better way to do this! =D

It's inherently not intuitive for the default database.type to be the final database and not the starting database.

To avoid this whole replacing stuff (replacing is also bad if we want loose coupling because if those property names ever change it won't work anymore, and I still think BChan will reject it and ask a lot of questions), we should have the HSQL to MySQL tests have database.type=hsql (as opposed to having them use database.type=mysql).

And we'll utilize the antCommand function to build the database for us!

Something like...

```
<execute function="AntCommand" locator1="build-test.xml" value1="rebuild-database -Ddatabase.type=mysql -Ddelete.liferay.home=false" />

**Pull request closed without merging**
