### PR TITLE
master-qa-14798

### PR DESCRIPTION
**Pull request by jaredzimmerman1**
https://issues.liferay.com/browse/LRQA-14851
https://issues.liferay.com/browse/LRQA-14901
https://issues.liferay.com/browse/LRQA-14798

### CODE REVIEW

**Comment by jaredzimmerman1** [comment]
@kenjiheigel,

- This pr adds PGCalendar#SCHEDULER_EVENT_DIALOG_BOX_USERS_LABEL and PGCalendar#SCHEDULER_EVENT_DIALOG_BOX_USERS_FIELD.

**Comment by jaredzimmerman1** [comment]
@brianchiu, rebased, fixed conflicts and pushed to origin.

**Comment by jaredzimmerman1** [comment]
@kenjiheigel,

- This pr adds a number of paths to PGCalendart.path and PGCalendarAddevent.path.
- It also adds CalendarConfiguration.path already in the new format.

**Comment by brianchiu** [comment]
SF for JZimmerman / VWare.

@jaredzimmerman1 @vicnate5 
Added extra line breaks for when there functions/macros where the order in which steps are executed matter for the test (so this applies to things like clicks, select frames, etc) and we'll have no extra line breaks for things where the order of execution doesn't matter (like typing, asserting). When I say "matter" I mean that it changes the outcome of the test if you those steps in a different order. It "matters" that you click save before you assert a success message. But it doesn't "matter" if you type in content before title or if you assert a description before you assert the summary (and both are on the same page).

I'll have a wiki for this soon.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal-ee/pull/9605
https://github.com/brianchandotcom/liferay-portal-ee/pull/9604
https://github.com/brianchandotcom/liferay-portal/pull/25538

**Pull request closed without merging**
