### PR TITLE
DON'T MERGE: Apply liferay-npm-bundler in layout-admin-web

### PR DESCRIPTION
**Pull request by julien**
Hi @brianchiu,

I wanted to ask you if you could test this branch and tell me if everything is working as expected.

The goal was to use the new liferay-npm-bundler in the layout-admin-web module.

Thanks in advance for your help.

/cc @kyle-miho
/cc @ealonso
/cc @jkappler

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Hey @julien 

There are some problems in the pull. Could you take a look?
```
java.lang.IllegalArgumentException: Path [layout-admin-web/js/miller_columns/Layout.es.js] does not start with a "/" character
java.lang.IllegalArgumentException: Path [layout-admin-web/js/miller_columns/Layout.es.js] does not start with a "/" character
```

**Comment by julien** [comment]
Hi @brianchiu,

Thanks. I just fixed those errors, when you have time could you please check again.

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@julien 
Thanks for sending it again!

So, here's what it's running into now:
There is some problem with the page template editor. Clicking the "available" tab does not show any fragments, and I am unable to select fragments to add, and there seems to be some sort of javascript problem.

**Comment by julien** [comment]
@brianchiu thanks for taking a look at that and reporting the errors.
Since, I'm not really familiar with these modules, I sent a PR to p2kmgcl [here](https://github.com/p2kmgcl/liferay-portal/pull/171)

**Pull request closed without merging**
