### PR TITLE
master-en-48

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-14944

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama @koor4356 

How does removing the pause fix the issue? Would "click" work? The default in Click.function is "click" and not "clickAt".

```
	<command name="pauseClickAt">
		<execute argument1="1000" selenium="pause" />

		<execute selenium="mouseOver" />

		<execute function="Click#clickAt" />

		<execute selenium="assertJavaScriptErrors" />

		<execute selenium="assertLiferayErrors" />
	</command>
```

```
	<command name="clickAt">
		<execute selenium="waitForVisible" />

		<execute selenium="mouseOver" />

		<execute selenium="clickAt" />

		<execute selenium="assertJavaScriptErrors" />

		<execute selenium="assertLiferayErrors" />
	</command>
```

**Comment by koor4356** [comment]
I think pauseClickAt uses mouseOVer first before clicking at the element,
while clickAt uses waitForVisible and then mouseOver after the element is
visible. I think when mouseOVer is called before element, it results in
null and this caused test to fail. I investigate and run this, and i was
able to get null with pauseClickAt command. But when I changed it to
clickAt, it works fine and test was passing.

I chooses not to use click because the author didn't use click when this
was written. so I assume click is not working. So i didn't try.

Thanks.

**Comment by brianchiu** [comment]
@koor4356 

Can you see if it works using the default click?

Another question I have - do you still need the pause?

**Comment by koor4356** [comment]
I just run this with Click command and it works. Unless someone need pause,
but I don't need it.

**Comment by brianchiu** [comment]
@evannagayama @koor4356 

Then I'm changing it to a click. Thanks.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25571

**Pull request closed without merging**
