### PR TITLE
master-qa-18955

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-18955

### CODE REVIEW

**Comment by brianchiu** [comment]
CC @juliocamarero

This would add the "addSite" test to the PR tester which adds a blank site.

**Comment by brianchiu** [comment]
source formatter test failure is unrelated

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31555

**Comment by juliocamarero** [comment]
:+1:

**Pull request closed without merging**
