### PR TITLE
master-qa-19286

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-19286

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama

removing the test

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31946

**Pull request closed without merging**
