### PR TITLE
LPS-97429 Ping server when offline

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:bundle

**Comment by p2kmgcl** [comment]
ci:test

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
PR submitted to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/75474

**Comment by p2kmgcl** [comment]
@brianchiu it was closed, sending it again today

**Pull request closed without merging**
