### PR TITLE
LPS-89154 Moves code to base class

### PR DESCRIPTION
**Pull request by ealonso**
Hey @brianchiu @kyle-miho,

We've updated the way we are editing Layout Templates of type content and Display Pages, right now we are using the edit mode, like in content pages.

I think that theese changes are going to break some poshi tests, Could you please take a look at it?

Also, I would like that you guys test it carefully and let me know if we are breaking something with this pull.

Could you please prioritize this pull? With this code we are blocking other stories, so we need to merge it on master as soon as possible.  I'm going to be pending to your comments all the day to fix all the regressions.

Thanks!!

cc: @jkappler @pavel-savinov

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by ealonso** [comment]
ci:test

**Comment by brianchiu** [comment]
@ealonso @pavel-savinov @jkappler 

Kyle and I have done some testing on it and here are the issues we've found. We don't see anything bad enough to stop the pull from going in, and we are going to work around some the test failures.

I have sent the pull to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/67392

Here are the issues we found:



1) After clicking "Publish", for both page templates and display pages, the page redirects to the "View Mode" of the page (which is hidden).

2) After clicking "Publish", for both page templates and display pages, there is no success message.

3) There is no "Back" button on the edit screen.

cc @kyle-miho

**Pull request closed without merging**
