### PR TITLE
master-qa-20421

### PR DESCRIPTION
**Pull request by vicnate5**
Resend of https://issues.liferay.com/browse/LRQA-20421

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Sorry. It should be fixed now

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchiu** [comment]
@alee8888

Hey Albert, 

Please see this setup wizard failure. This has happened (rarely) on some of BChan's other pulls as well. BLee has already done some investigation today.

CC @xbrianlee

**Comment by brianchiu** [comment]
SF for VWare.

@vicnate5 
I changed the success messages in CalendarEvent.macro to just use Alert#viewRequestCompletedSuccessMessage

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34219

**Pull request closed without merging**
