### PR TITLE
LRQA-22513 Report any errors found in db_upgrade_log.

### PR DESCRIPTION
**Pull request by pyoo47**
I've tested the java code contained within the beanshell tag and it works fine. I didn't, however, test it using ant so there's a possibility that there's a syntax or import problem that didn't come out during my java testing. If any issues come up just call me over and I should be able to fix it for you immediately.

### CODE REVIEW

**Comment by brianchiu** [comment]
Alright.

Looks like there are some other loopholes we have to account for.

This one I'm fairly certain we can ignore.
* [java] 00:12:47,532 ERROR [main][SecurityManagerUtil:60] Plugin security management is not enabled. Enable a security manager, then restart.

These are probably bugs. I'm filing a ticket.
* [java] 00:13:18,519 ERROR [main][UpgradeMVCCVersion:54] Table LayoutFriendlyURL does not exist

These are properties that our tests pass in. They look to be obsolete, but if that's the case, the documentation needs to be updated. Our tests get these properties from the documentation.
* [java] 00:13:53,203 ERROR [main][VerifyProperties:149] Portal property "hibernate.cache.use_query_cache" is obsolete

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Alright, last one to ignore (See: https://issues.liferay.com/browse/LRQA-7650):

[java] 22:53:45,678 ERROR [main][SecurityManagerUtil:60] Plugin security management is not enabled. Enable a security manager, then restart.

https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/2344/AXIS_VARIABLE=0,label_exp=!master//console

**Comment by pyoo47** [comment]
ci:retest

**Pull request closed without merging**
