### PR TITLE
master-jz-53

### PR DESCRIPTION
**Pull request by jaredzimmerman1**
https://issues.liferay.com/browse/LRQA-15222

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5 @jaredzimmerman1 

How come you're seemingly asserting that both the start and end date show the same day?
```
	<command name="viewWeekStartDayViaEventMiniCalendar">
		<execute function="Click" locator1="PGCalendarAddevent#START_DATE" />

		<execute function="AssertTextEquals" locator1="PGCalendarAddevent#MINI_CALENDAR_WEEK_START_DAY" value1="${weekStartDay}" />

		<execute function="Click" locator1="PGCalendarAddevent#END_DATE" />

		<execute function="AssertTextEquals" locator1="PGCalendarAddevent#MINI_CALENDAR_WEEK_START_DAY" value1="${weekStartDay}" />
	</command>
```

**Comment by vicnate5** [comment]
@brianchiu 

weekStartDay refers to a calendar configuration setting. The day of the week that a week starts on should be the same across all of Calendar. Asserting this is the purpose of the tests that uses that macro.

**Comment by brianchiu** [comment]
Ok. that's fine.

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26680
https://github.com/brianchandotcom/liferay-portal-ee/pull/10089
https://github.com/brianchandotcom/liferay-portal-ee/pull/10090

**Pull request closed without merging**
