### PR TITLE
master-qa-16382

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-16382

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchiu 
The commits didn't cherry pick cleanly into ee-6.2.x/ee-6.1.x so I had to manually make the changes in those branches.

This fixes the issue when running any Poshi test that starts more than one bundle. In the start-app-server-cmd, "<antcall target="delete-liferay-home" />" was recently added. So when another bundle tries to start, the script will try to delete liferay home from the original bundle, which is already running. This causes the second bundle to timeout and not start.

**Comment by brianchiu** [comment]
@alee8888 
Can we have the set-app-server-properties conditional nested inside the delete.liferay.home conditional? Because if delete.liferay.home is set to false, it won't need it anyways.

**Comment by alee8888** [comment]
@brianchiu I updated the target to nest set-app-server-properties across all the branches. Thanks.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27645
https://github.com/brianchandotcom/liferay-portal-ee/pull/10483
https://github.com/brianchandotcom/liferay-portal-ee/pull/10484
https://github.com/brianchandotcom/liferay-portal-ee/pull/10485
https://github.com/brianchandotcom/liferay-portal-ee/pull/10486

**Pull request closed without merging**
