### PR TITLE
master-qa-14945

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-14945

### CODE REVIEW

**Comment by brianchiu** [comment]
Pushed back to SChoi / AChiang.

@sharonchoi @austinchiang 

1. For ee-6.2.x/ee-6.2.10, fix so that it has all 3. 
2. For master, there should only be 1 locator there and not 2. Can you remove the ones that are wrong?

**Comment by sharonchoi** [comment]
@brianchiu force pushed updates

**Comment by brianchiu** [comment]
SF for AChiang / SChoi.

@sharonchoi @austinchiang 
I sorted the locator keys in the ee-6.2.x/ee-6.2.10. The reason why is because a slash comes before "a".

http://www.asciitable.com/

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal-ee/pull/9645
https://github.com/brianchandotcom/liferay-portal-ee/pull/9644
https://github.com/brianchandotcom/liferay-portal/pull/25615

**Pull request closed without merging**
