### PR TITLE
LPS-96737 Use sandbox to allow variable name clash and surround with quotes

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
Everything looks good. There are no unique failures, and I've manually tested the fix as well to make sure asset publisher widget works. I'll forward this to BChan.

**Comment by victorg1991** [comment]
Thanks @brianchiu :)

**Comment by brianchiu** [comment]
PR submitted to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74604

**Pull request closed without merging**
