### PR TITLE
master-en-140

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-16424

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@brianchiu I updated the pr with the fixes. For this one I left commit message as "SF" because I had already made a lot of changes. In the future I'll make sure to have the correct message.

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27837

**Pull request closed without merging**
