### PR TITLE
LPS-81454 Update english translation for group pages portlet

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Hey @brianchiu, this will probably break a lot of tests cuz of the renaming, so that's why I'm sending to you. Let me know what you think. Thanks in advance

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Testing it here:
https://github.com/brianchiu/liferay-portal/pull/1631

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/59027

**Pull request closed without merging**
