### PR TITLE
master-qa-17933

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-17933

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
I'll look into this. I don't think those failures are caused by your commits.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
You forgot to put an LRQA ticket number before your ticket. I'm putting that in.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/30224

**Pull request closed without merging**
