### PR TITLE
master-qa-21364

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-21364

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
This one is fine now. Those 2 failures have been fixed.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34785

**Pull request closed without merging**
