### PR TITLE
master-vw-80

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-19652

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Hey Victor, can you rebase this? I wasn't able to rebase w/o errors.

**Comment by brianchiu** [comment]
Hey @vicnate5 , can you rebase this? I wasn't able to rebase w/o errors.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@brianchiu rebased

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32863

**Pull request closed without merging**
