### PR TITLE
LPS-91291 SF

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @brianchiu,
This one breaks some POSHI tests for sure. Now we have a publish button in the standard pages editor. When you create a new standard page or edit the existing one the changes are not applied immediately, they exist only for the Draft page(in the Edit mode) and you have to publish them explicitly(as it happens with the page templates).
Once published you can switch to the View mode and see the changes.

/cc @ealonso

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Pull request closed without merging**
