### PR TITLE
master-sc-32

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-14423

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@sharonchoi @simonkpark 

Can you resolve the rebase errors?

**Comment by sharonchoi** [comment]
@brianchiu fixed and force pushed

**Comment by brianchiu** [comment]
@sharonchoi 

Send a new pull. I can't reopen this one.

**Pull request closed without merging**
