### PR TITLE
LPS-85305 Avoid duplicate entries

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
@brianchiu, just a test to see how many functional tests will brake because of the changes

**Comment by jkappler** [comment]
ci:reopen

**Comment by brianchiu** [comment]
@jkappler 
It seems the main cause of the functional test failure is that the HTML of the select web content (in the WCD widget) changed? It doesn't seem to be a bug though.

Otherwise, there is a staging test failure that I think is unrelated because it tried to navigate to the site home page but timed out.

**Pull request closed without merging**
