### PR TITLE
poshi-conditionals

### PR DESCRIPTION
**Pull request by brianchiu**
poshi-conditionals

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:stop

**Comment by sharonchoi** [comment]
ci:stop

**Comment by sharonchoi** [comment]
ci:retest:gauntlet

**Comment by michaelhashimoto** [comment]
ci:retest:gauntlet

**Comment by brianchiu** [comment]
Second Iteration here:
https://github.com/brianchiu/liferay-portal/pull/1582

**Pull request closed without merging**
