### PR TITLE
LPS-90279 Adjust contextual sidebar top

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
Hi @ealonso 
Could you take a look at this pull again? Right now, I cannot localize web content because the side bar (which looks great! it really helps consolidate the page) is blocking the localization buttons.

cannot-localize

**Comment by ealonso** [comment]
cc: @pavel-savinov

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Pull request closed without merging**
