### PR TITLE
master-en-167

### PR DESCRIPTION
**Pull request by evannagayama**
master-qa-18283

### CODE REVIEW

**Comment by brianchiu** [comment]
SF for ENagayama / AChu.

@evannagayama @anthony-chu 
I changed the "Blogs#addWithTag" to use "Blogs#addEntryWithTag" and "Blogs#addEntryWithTags". Those macros are more 'properly' named and also make use of the newer way that we write macros (less conditionals). Those also make use of AssetCategorization.macro.

**Comment by evannagayama** [comment]
@brianchiu, thanks. Should we then replace the other test with  Blogs#addWithTag and delete the old one?

**Comment by brianchiu** [comment]
@evannagayama 
I replaced all instances of addWithTag and removed the macro.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/30718

**Pull request closed without merging**
