### PR TITLE
LPS-90985 Not needed since we are no longer using pop-ups

### PR DESCRIPTION
**Pull request by ealonso**
Hey @brianchiu @kyle-miho,

In this pull we are removing the pop-up when we are adding new elements from asset publisher or web content display. Right now we are opening the editors on the same page.

Please let us know if you need some aditional changes.

Thanks!!
Eudaldo

cc: @pavel-savinov

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@ealonso Good to know. Thanks for sending this to us.

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
Hey @ealonso 
There is a compile failure. Can you take a look?

```
     [exec] > Task :apps:asset:asset-publisher-web:compileJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/internal/server/taglib/util/AssetEntryActionDropdownItemsProvider.java:74: error: cannot find symbol
     [exec] 								PortletDisplay portletDisplay =
     [exec] 								^
     [exec]   symbol: class PortletDisplay
```

**Comment by ealonso** [comment]
Hey @brianchiu,
I've updated the pull request with the fixes.
Thanks!!

**Comment by brianchiu** [comment]
@ealonso Got it! Thanks for explaining it!

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
Oops. Forgot to close this.

Pull request was sent to BChan here:
https://github.com/brianchandotcom/liferay-portal/pull/68743

**Pull request closed without merging**
