### PR TITLE
master-en-104

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-9441

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by evannagayama** [comment]
@brianchiu could you prioritize this pr? We have some other tests waiting on this pr. Thanks.

**Comment by brianchiu** [comment]
@evannagayama 
Yeah. This will get in the next batch.

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
SF for ENagayama / BWulbern.

@evannagayama @brianwulbern 
I added line breaks for the logical breaks.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26928

**Pull request closed without merging**
