### PR TITLE
LRQA-32905

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-32905

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:stop

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to KHeigel.
https://github.com/kenjiheigel/liferay-portal/pull/365

**Pull request closed without merging**
