### PR TITLE
LRQA-43905 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-43905

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
This could possibly break some tests, there are way too many tests changed to be able to make an easy query to test them all.

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:test

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64067
https://github.com/brianchandotcom/liferay-portal-ee/pull/21983

**Pull request closed without merging**
