### PR TITLE
test

### PR DESCRIPTION
**Pull request by brianchiu**
test

### CODE REVIEW

**Comment by brianchiu** [comment]
@michaelhashimoto @pyoo47

Hey guys, can you look into what's wrong? (Don't worry about the Forms test failures). I'm trying to test db upgrades, but it seems almost like the liferay-qa-portal-legacy-ee is missing?

CC @sharryxue

**Comment by pyoo47** [comment]
I'll get together with Hashi this morning when he gets in to go over this.

**Comment by pyoo47** [comment]
We've created a ticket for this issue. Hashi and I will be working it together.
https://issues.liferay.com/browse/LRQA-22334

**Comment by michaelhashimoto** [comment]
@brianchiu - i'm trying this out again here:
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/896/

**Comment by michaelhashimoto** [comment]
@brianchiu - it looks like it's okay.

https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16468/AXIS_VARIABLE=0,label_exp=!master/consoleFull

Thanks!

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-jenkins-ee/pull/1321

**Comment by brianchiu** [comment]
@pyoo47 @michaelhashimoto 
Thanks guys!

There are some poshi errors that I don't know why they happened... but I can take it from here.

**Comment by michaelhashimoto** [comment]
I re-ran the test.. the failure could have been a fluke..
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/900/

**Comment by brianchiu** [comment]
added a new commit to address this

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Pull request closed without merging**
