### PR TITLE
LPS-85566 Handle only add menu drop down item events to avoid confusion with the languages menu for localized inputs

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @brianchiu, some of my last pulls were quite buggy, sorry for that and thanks for being on the alert!

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
@pavel-savinov 
Thanks. This pull looks good to me. I'll send this to BChan.

**Comment by brianchiu** [comment]
Pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68574

**Comment by kyle-miho** [comment]
ci:test:bundle

**Pull request closed without merging**
