### PR TITLE
LRQA-44290 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-44290
Can't apply this to 7.1.x currently until the WC JSON API gets released in 7.1.x SP2

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64660

**Pull request closed without merging**
