### PR TITLE
master-qa-23893

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-23893

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
Those failures have been fixed now. I'm going to retest this

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38715

**Pull request closed without merging**
