### PR TITLE
master-qa-18243

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-18243

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kenjiheigel 
Can you backport the build-test.xml stuff to 6.2 and 6.1?

**Comment by kenjiheigel** [comment]
I've sent the additional pulls here:
https://github.com/brianchiu/liferay-portal-ee/pull/4264
https://github.com/brianchiu/liferay-portal-ee/pull/4265
https://github.com/brianchiu/liferay-portal-ee/pull/4266
https://github.com/brianchiu/liferay-portal-ee/pull/4267

**Comment by brianchiu** [comment]
SF for KHeigel.

@kenjiheigel 
As we discussed, I moved the sign out of portal instance macro to the portal instance tear down and changed the "property-value" to a TestPropsUtil call.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/30973
https://github.com/brianchandotcom/liferay-portal-ee/pull/11667
https://github.com/brianchandotcom/liferay-portal-ee/pull/11668
https://github.com/brianchandotcom/liferay-portal-ee/pull/11669
https://github.com/brianchandotcom/liferay-portal-ee/pull/11670

**Pull request closed without merging**
