### PR TITLE
LRQA-32486 | master

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-32486

### CODE REVIEW

**Comment by brianchiu** [comment]
@anthony-chu could you review this since it affects web content stuff?

@kmaria does this need to also be backported to ee-7.0.x? I saw on the ticket that it has both master and ee-7.0.x listed but there's only a master pull.

**Comment by anthony-chu** [comment]
@brianchiu @kmaria

it looks like there might be a bug with the web content display portlet, where the messaging in the web content display portlet differs in a staged site versus an unstaged site. i've filed a bug ticket here - [LPS-72470](https://issues.liferay.com/browse/LPS-72470). if it turns out to be a bug, we can merge this and apply it to the rest of the wcm tests that use this macro as well. i'll keep you guys posted. thanks!

**Comment by kmaria** [comment]
@anthony-chu Thanks, Anthony.
@brianchiu if the test fix is needed, I will send it to Ginson.

**Comment by brianchiu** [comment]
@anthony-chu 
Any updates on this?

**Comment by anthony-chu** [comment]
@brianchiu there's no update on the ticket yet. it was In Progress earlier this week, but it's been moved back to Verified.

**Comment by anthony-chu** [comment]
@brianchiu @kmaria The pull for [LPS-72470](https://issues.liferay.com/browse/LPS-72470) has been merged into the com-liferay-journal sub-repo, but it has not yet been merged into central due to several unrelated test failures on pull request tester.

**Comment by kmaria** [comment]
Thanks for the info, @anthony-chu

**Comment by anthony-chu** [comment]
@kmaria I forwarded the PR to BChan. I made a change to rename the macro since the message only applies to entries in the Recycle Bin. I repurposed the old macro to view the message for articles that have been deleted. Thanks for making the changes!

@brianchiu This PR can be closed. Thanks!

**Comment by anthony-chu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/49037

**Comment by kmaria** [comment]
@anthony-chu Thank you. Is backport needed/sent? 
cc @brianchiu

**Comment by anthony-chu** [comment]
Hi @kmaria,

A backport for LRQA-32486 won't be necessary, since LPS-72470 and LPS-72063 were changes made only to master, so LRQA-32486 was sent to master only.

**Comment by brianchiu** [comment]
Cool. Thanks, @anthony-chu

**Pull request closed without merging**
