### PR TITLE
master-qa-14798

### PR DESCRIPTION
**Pull request by jaredzimmerman1**
https://issues.liferay.com/browse/LRQA-14798

### CODE REVIEW

**Comment by jaredzimmerman1** [comment]
@kenjiheigel, I've added two new paths with this pr:
- PGCalendar#SCHEDULER_EVENT_DIALOG_BOX_USERS_LABEL
- PGCalendar#SCHEDULER_EVENT_DIALOG_BOX_USERS_FIELD

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@jaredzimmerman1 

Please fix rebase errors and resend.

**Comment by jaredzimmerman1** [comment]
@brianchiu,

Fixed and pushed to head. You can reopen this pr.

**Comment by jaredzimmerman1** [comment]
Pushed to BChiu.
- ee-6.2.10 - https://github.com/brianchiu/liferay-portal-ee/pull/3691
- ee-6.2.x - https://github.com/brianchiu/liferay-portal-ee/pull/3692
- master -https://github.com/brianchiu/liferay-portal/pull/120

**Pull request closed without merging**
