### PR TITLE
LPS-96438 Since it's now a public layout, we have to establish the corresponding permissions

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
hey @brianchiu, @kyle-miho. This should fix the display page issue. I'm sending it to you first so you can check if everything's ok, and want to add the poshi test to this pull.

Thanks!

cc:// @ealonso

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Cool. I'm working on the automated test.

**Comment by brianchiu** [comment]
PR submitted to BChan with the automated test.
https://github.com/brianchandotcom/liferay-portal/pull/74381

**Pull request closed without merging**
