### PR TITLE
master-qa-19240

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-19240

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama 

Getting macros and tests off of, and emoving, old path files

**Comment by brianwulbern** [comment]
Strange, it worked on [Friday](https://github.com/brianwulbern/liferay-portal/pull/123#issuecomment-156655410)

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32246

**Pull request closed without merging**
