### PR TITLE
LPS-92241 Added resizer to columns

### PR DESCRIPTION
**Pull request by p2kmgcl**
Related LPS:
https://issues.liferay.com/browse/LPS-90056
https://issues.liferay.com/browse/LPS-92236
https://issues.liferay.com/browse/LPS-92240
https://issues.liferay.com/browse/LPS-91982
https://issues.liferay.com/browse/LPS-92241

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
@p2kmgcl There is a rebase error. I'll try a little later to see if I can resolve it, but if I can't, I will need your help.

**Comment by brianchiu** [comment]
Fixed rebase error and resent to myself here:
https://github.com/brianchiu/liferay-portal/pull/1816

**Pull request closed without merging**
