### PR TITLE
LPS-86192 Set view in context as the default link behaviour for any asset

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
hey @brianchiu, @kyle-miho, we changed the behavior of the asset publisher portlet so that the view in context is the default value (mostly because of display pages). I'm not sure if this will break any tests, so I prefer to run this through you first.

Thanks!

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
Pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/65323

**Pull request closed without merging**
