### PR TITLE
master-qa-15232

### PR DESCRIPTION
**Pull request by jaredzimmerman1**
https://issues.liferay.com/browse/LRQA-15232

### CODE REVIEW

**Comment by brianchiu** [comment]
Pushed back to JZimmerman.

@jaredzimmerman1 

1. Rename microsoft_outlook_calendar.ics to something that has "Calendar" or some other indicator at the beginning to indicate that the dependency belongs to calendar.

2. Remove extra row at end of CalendarManageCalendars.path

**Comment by jaredzimmerman1** [comment]
@brianchiu 
Updated pull with changes above.

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26095
https://github.com/brianchandotcom/liferay-portal-ee/pull/9840
https://github.com/brianchandotcom/liferay-portal-ee/pull/9841

**Pull request closed without merging**
