### PR TITLE
Poshi project configuration files

### PR DESCRIPTION
**Pull request by jtydhr88**
Hi Brain,
this commit included two poshi ide project configuration files and make esay to poshi files import to Poshi IDE.

### CODE REVIEW

**Comment by gamerson** [comment]
hey @jtydhr88 is "trunk-test" the name that the QA team would like it to be called?

**Comment by brianchiu** [comment]
Hi @jtydhr88 @gamerson 

Thanks for all your work on Poshi IDE! I definitely look forward to seeing it.

I'm probably not a qualified person to review this, as I don't know much about eclipse.
1. Do your commits have any ticket numbers or an associated JIRA project?
2. Is "trunk-test" something like the project name?
3. I'm also not super sure if BChan would allow committing these files? But I could be wrong.

CC @michaelhashimoto
CC @karendang

**Comment by gamerson** [comment]
Thanks Brian for your thoughts.

So for #1 we can create the JIRA ticket and associate it there.

For #2, what project name does QA team like?  It can be anything but it
should be something that you guys discuss and give it a name.

#3 BChan should be ok if he knows the QA team is adopting PoshiIDE to use
for Poshi users (testers).  Since the portal already has many other
.project files scattered throughout the hierarchy of the portal project
tree.

On Fri, Jul 17, 2015 at 6:35 AM, Brian Chiu <notifications@github.com>
wrote:

> Hi @jtydhr88 <https://github.com/jtydhr88> @gamerson
> <https://github.com/gamerson>
>
> Thanks for all your work on Poshi IDE! I definitely look forward to seeing
> it.
>
> I'm probably not a qualified person to review this, as I don't know much
> about eclipse.
> 1. Do your commits have any ticket numbers or an associated JIRA project?
> 2. Is "trunk-test" something like the project name?
> 3. I'm also not super sure if BChan would allow committing these files?
> But I could be wrong.
>
> CC @michaelhashimoto <https://github.com/michaelhashimoto>
> CC @karendang <https://github.com/karendang>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchiu/liferay-portal/pull/518#issuecomment-122122799>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by brianchiu** [comment]
@jtydhr88 @gamerson 

1. Cool.
2. It can be anything? I looked at existing .project files and saw that they were always named after the module or folder they resided in plus a designation of what branch (which would make ours portalweb-master). Is it ok to deviate from what appears to be the standard? If so, I'll talk with some others in QA about it.
3. Alright. Sounds good. What about the org.eclipse.wst.validation.prefs file? I don't see any of those scattered throughout. My assumption is that this has the custom validation preferences for poshi?

**Comment by gamerson** [comment]
Hey Brian,

2. Yes anything and "portalweb-master" makes the most sense considering the
standard.  Terry can you make that change to your pull request when you
resend it?
3. Yes org.eclipse.wst.validation.prefs file is custom validation settings
for poshi-ide (and all other xml validation settings in Eclipse)




On Fri, Jul 17, 2015 at 8:18 AM, Brian Chiu <notifications@github.com>
wrote:

> @jtydhr88 <https://github.com/jtydhr88> @gamerson
> <https://github.com/gamerson>
>
>    1. Cool.
>    2. It can be anything? I looked at existing .project files and saw
>    that they were always named after the module or folder they resided in plus
>    a designation of what branch (which would make ours portalweb-master). Is
>    it ok to deviate from what appears to be the standard? If so, I'll talk
>    with some others in QA about it.
>    3. Alright. Sounds good. What about the
>    org.eclipse.wst.validation.prefs file? I don't see any of those scattered
>    throughout. My assumption is that this has the custom validation
>    preferences for poshi?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchiu/liferay-portal/pull/518#issuecomment-122135541>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by jtydhr88** [comment]
Hey Brian,
1, What's the project I should choose in JIRA?LPS or Liferay QA?
2. What's project name you think well? "portalweb-master"?

**Comment by brianchiu** [comment]
Hey Terry,

1. What project do you guys normally use for your IDE commits? If you guys don't have one, use LRQA.
2. Just having it as "portalweb-master", even though it follows the standard, is a little bit confusing because it doesn't really represent what it is, and there is also a portal-web folder.

Can we have it be "test-functional-master"?

Also, a couple other questions
- how hard is it to change the project name later on? Does trying to do so present a lot of complications?
- is this going to be backported into the 6.2 and 6.1 branches?

**Comment by jtydhr88** [comment]
1, We normally use IDE-xxxx for IDE tickets.But we didn't create any JIRA tickets for poshi IDE.I think LRQA is a good choose in this case.
2. It's very easy to change the project name in your own eclipse env. The name we are talking about just is a default name, users can change it to everything their like in their own machine.(But need attention, that means you will change ".project" file when you changed the project name. you need pay a attention when you do any git commit).
3, If you guys need to import the 6.2/6.1 poshi files to Poshi IDE, I think it should be backported into those two branckes.

For next I will create a LRQA ticket and change the project name to "test-functional-master" then I resend the PR to you, right?

**Comment by brianchiu** [comment]
Sure. Sounds good to me.

1. Create LRQA ticket and commit under that / change project name to "test-functional-master"
2. Resend PR to me.
3. We will also need these in 6.2 and 6.1, but maybe for now let's keep it to master since we're still trying things out.

As I've said before though, I'm not really qualified to review this, so I'd pretty much just be passing along your commits to BChan.

CC @gamerson

**Comment by gamerson** [comment]
Has anyone told BChan about PoshiIDE ?  We probably should give him some
context for that new plugin before we send him the pull.

On Sat, Jul 18, 2015 at 9:40 AM, Brian Chiu <notifications@github.com>
wrote:

> Sure. Sounds good to me.
>
>    1. Create LRQA ticket and commit under that / change project name to
>    "test-functional-master"
>    2. Resend PR to me.
>    3. We will also need these in 6.2 and 6.1, but maybe for now let's
>    keep it to master since we're still trying things out.
>
> As I've said before though, I'm not really qualified to review this, so
> I'd pretty much just be passing along your commits to BChan.
>
> CC @gamerson <https://github.com/gamerson>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchiu/liferay-portal/pull/518#issuecomment-122466272>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
I'll chat with Bchan on Monday and will let him know about poshiide and the
changes we need to the portalweb folder.

On Friday, July 17, 2015, Greg Amerson <gregory.amerson@liferay.com> wrote:

> Has anyone told BChan about PoshiIDE ?  We probably should give him some
> context for that new plugin before we send him the pull.
>
> On Sat, Jul 18, 2015 at 9:40 AM, Brian Chiu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Sure. Sounds good to me.
>>
>>    1. Create LRQA ticket and commit under that / change project name to
>>    "test-functional-master"
>>    2. Resend PR to me.
>>    3. We will also need these in 6.2 and 6.1, but maybe for now let's
>>    keep it to master since we're still trying things out.
>>
>> As I've said before though, I'm not really qualified to review this, so
>> I'd pretty much just be passing along your commits to BChan.
>>
>> CC @gamerson <https://github.com/gamerson>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brianchiu/liferay-portal/pull/518#issuecomment-122466272>
>> .
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>


-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by brianchiu** [comment]
That sounds great. Thanks, Greg.

**Pull request closed without merging**
