### PR TITLE
LPS-61956 Update jar

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@jhendley said you could help to run the regressions check.

Please get this done by the end of today, we have a lot stuff depend on it.

Thanks @brianchiu !

**Comment by brianchiu** [comment]
@shuyangzhou 
Sure thing. This will run through the acceptance tests in the PR tester.

Additionally, we'll make sure the issues in this filter are not reproducible.
https://issues.liferay.com/issues/?filter=32080

**Comment by shuyangzhou** [comment]
Awesome, thanks @brianchiu !

**Comment by brianchiu** [comment]
That's a good sign. Passed all frontend PR tester tests. Source Formatter test failure seems unrelated.

```
Error Message

org.junit.ComparisonFailure: ../../../modules/portal-security/portal-security-sso-google/src/main/resources/content/Language.properties expected:<...oogle
google-client-[]secret=Google Client...> but was:<...oogle
google-client-[id=Google Client ID
google-client-]secret=Google Client...>
Stacktrace

org.junit.ComparisonFailure: ../../../modules/portal-security/portal-security-sso-google/src/main/resources/content/Language.properties expected:<...oogle
google-client-[]secret=Google Client...> but was:<...oogle
google-client-[id=Google Client ID
google-client-]secret=Google Client...>
```

**Comment by brianchiu** [comment]
@shuyangzhou 

Alright. This looks good. I tested those 9 tickets and was unable to reproduce any of the failures on there.

CC @jhendley

**Comment by shuyangzhou** [comment]
Awesome! Thanks @brianchiu !

**Pull request closed without merging**
