### PR TITLE
master-qa-14333

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-14333

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama 

I got rebase errors. They're not difficult to resolve, but I'm not sure what it's supposed to be.

```
First, rewinding head to replay your work on top of it...
Applying: LRQA-14333 - paths
Applying: LRQA-14333 - macros
Using index info to reconstruct a base tree...
M       portal-web/test/functional/com/liferay/portalweb/macros/Bookmark.macro
M       portal-web/test/functional/com/liferay/portalweb/macros/Category.macro
M       portal-web/test/functional/com/liferay/portalweb/macros/Vocabulary.macro
Falling back to patching base and 3-way merge...
Auto-merging portal-web/test/functional/com/liferay/portalweb/macros/Vocabulary.macro
CONFLICT (content): Merge conflict in portal-web/test/functional/com/liferay/portalweb/macros/Vocabulary.macro
Auto-merging portal-web/test/functional/com/liferay/portalweb/macros/Category.macro
CONFLICT (content): Merge conflict in portal-web/test/functional/com/liferay/portalweb/macros/Category.macro
Auto-merging portal-web/test/functional/com/liferay/portalweb/macros/Bookmark.macro
Failed to merge in the changes.
Patch failed at 0002 LRQA-14333 - macros
The copy of the patch that failed is found in:
   l:/public/master-portal/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://issues.liferay.com/browse/LRQA-14333

**Pull request closed without merging**
