### PR TITLE
master-kh-33

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-13985 9dff458...3e757ad
https://issues.liferay.com/browse/LRQA-13969 3e757ad...5914d18

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchiu** [comment]
SF for KHeigel

@kenjiheigel 
Added an extra row before the header in SearchResults.path.
Renamed https://github.com/kenjiheigel/liferay-portal/commit/8ed599b04c465d36d8ebd2b43ea11a79d9136eb9 commit so there is no dash and so that it uses imperative voice.

@sharonchoi 
Next time, split this up into 2 commits:
1. LRQA-13969 Fix label on locator-key for notification requests
2. LRQA-13969 Remove extra row
https://github.com/kenjiheigel/liferay-portal/commit/8ed599b04c465d36d8ebd2b43ea11a79d9136eb9

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26742

**Pull request closed without merging**
