### PR TITLE
master-qa-15214

### PR DESCRIPTION
**Pull request by kiyoshilee**
https://issues.liferay.com/browse/LRQA-15214

### CODE REVIEW

**Comment by jaredzimmerman1** [comment]
@brianchiu 
we talked with Kiyoshi about this. This fixes the issue.

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
@tiborkovacs Thanks!

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25958
https://github.com/brianchandotcom/liferay-portal-ee/pull/9770
https://github.com/brianchandotcom/liferay-portal-ee/pull/9771

**Pull request closed without merging**
