### PR TITLE
LPS-93116 Show name of the contributed/dynamic fragment in the section

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@brianchiu , @kyle-miho, I prefer to run this through you first. This should be also transparent to the user in terms of functionality

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchiu** [comment]
ci:test:bundnle

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:bundle:norebase

**Comment by brianchiu** [comment]
ci:test:relevant:norebase

**Comment by brianchiu** [comment]
PR forwarded to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/71491

**Pull request closed without merging**
