### PR TITLE
master-sc-43

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-15030

### CODE REVIEW

**Comment by sharonchoi** [comment]
@brianchiu pushing initial macro changes for blogs revamp

**Comment by brianchiu** [comment]
Pushed back to SChoi / SPark.

@sharonchoi @simonkpark 
1. Edit the "add" macro commands to have direct objects (e.g. addEntry)
2. Change Blogs#viewDetailsPG so that there isn't a long conditional there. You can just assert authorFullName rather than having to worry about whether or not there's a middle name or first name or last name.

**Comment by brianchiu** [comment]
SF for SChoi / SPark.

@sharonchoi @simonkpark 
You didn't take into account the fact that the conditional will assert "Test Test" if no author is set. I added a catch for this by making that variable set to "Test Test" by default as a global variable.

If you find that variable being needed outside of BlogsEntry.macro, you can set it in Blogs.macro.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26721

**Pull request closed without merging**
