### PR TITLE
master-en-99

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-15652

### CODE REVIEW

**Comment by evannagayama** [comment]
I think the commit could be combined into one like this, "LRQA-15652 Remove duplicate macro call and replace in test". What do you think @brianwulbern + @brianchiu?

**Comment by brianchiu** [comment]
@evannagayama @brianwulbern 

I agree with Evan. You should combine the two.

I would probably name it "LRQA-15652 Remove addCPWithStructure macro because it duplicates addWithStructureCP"

Any replacing you do in tests is implied.

**Comment by brianwulbern** [comment]
@evannagayama @brianchiu 

After committing it, I actually thought it should be reversed: 1) update the tests to use one macro call, 2) remove the duplicate (and incorrectly named) macro block.  This would be in accord with the logical flow we've used before, in https://github.com/brianchandotcom/liferay-portal/pull/26524

**Comment by brianchiu** [comment]
@evannagayama @brianwulbern 

What BWul proposed is also fine. If you do that though, don't call it "Remove duplicate macro call" because you're just removing the macro. "Duplicate macro call" is actually kind of ambiguous because it could also mean you're calling the same macro multiple times.

**Comment by brianchiu** [comment]
Bwul resent in:
https://github.com/brianchiu/liferay-portal/pull/281

**Pull request closed without merging**
