### PR TITLE
LPS-90446 Persist default portlet preferences before rendering fragment entry link with portlet

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchiu, sending it to you first just in case

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:msb

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
It passed the ci tests, and I also tested manually and the bug is fixed!

Pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68278

**Pull request closed without merging**
