### PR TITLE
LPS-58504

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LPS-58504

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianwulbern Wouldn't https://github.com/brianwulbern/liferay-portal/commit/9de876b84cfc597d073b4022c84a2e4771670489 break things because mouseOver doesn't have a wait for built into it?

**Comment by brianwulbern** [comment]
Oh, the test needs the Selenium commands to be switched like that with the new UI. I talked with @kenjiheigel about it, and he agreed that since it's a very specific function call, it would be fine to make the change as I did.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@brianchiu @kenjiheigel

I updated the function block to first use 'waitForElementPresent' before mouseOver and waitForVisible, the change works locally, but I just rebased and force pushed, let's see if it passes at head.

**Comment by brianchiu** [comment]
SF for BWulbern.

@brianwulbern 
You had an extra tab in the .function file.

**Comment by brianchiu** [comment]
@epgarcia @marcoscv-work 
I noticed one of the commits (https://github.com/brianwulbern/liferay-portal/commit/54f248ebbc89f8f557afe0f74fa61d1d397c8576) has LPS-57677 in the message. Is that commit supposed to be there? https://issues.liferay.com/browse/LPS-57677 is still in 'open' status.

**Comment by marcoscv-work** [comment]
Hi @brianchiu , sorry, actually the commit LPS-57677 is a LPS-58504 commit, I think that was an cherry-pick error, so if we change this commit title we could go ahead.

**Comment by brianchiu** [comment]
@marcoscv-work 
Ok. I'll just change that commit to say LPS-58504. Thanks.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/30553

**Comment by brianwulbern** [comment]
Hi guys,

Next Tuesday (4/4) China will be celebrating Qingming festival, and many on
the CNQA team will be taking the Monday (4/3) before it off.

With that in mind,* we will, more 'officially', need help checking on the
Pull Requests that go in on ee-7.0.x on those two days*.

You guys have already done a great job supporting CNQA during the 7.0
handoff, especially with all the backported SF refactoring, so we're
grateful for that :)

Thanks,

-- 
Brian Wulbern
Liferay, Inc.

**Comment by brianwulbern** [comment]
Hi，

   Thanks Bwulbern. I also created a loop so everyone knows incoming
holidays in China office
<https://loop.liferay.com:443/home/-/loop/feed/4663283>. For the Qingming
Holiday, Steven also inform in the skype DXP Fix Pack Release -RELEASE-552
chat group to inform related developers.   Thanks.

2017-03-29 16:35 GMT+08:00 Brian Wulbern <brian.wulbern@liferay.com>:

> Hi guys,
>
> Next Tuesday (4/4) China will be celebrating Qingming festival, and many
> on the CNQA team will be taking the Monday (4/3) before it off.
>
> With that in mind,* we will, more 'officially', need help checking on the
> Pull Requests that go in on ee-7.0.x on those two days*.
>
> You guys have already done a great job supporting CNQA during the 7.0
> handoff, especially with all the backported SF refactoring, so we're
> grateful for that :)
>
> Thanks,
>
> --
> Brian Wulbern
> Liferay, Inc.
>



-- 
Sophia Zhang
CNQA Manager
liferay.com
Enterprise. Open Source. For Life.

**Pull request closed without merging**
