### PR TITLE
LRQA-42406 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-42406
7.1.x: https://github.com/brianchiu/liferay-portal-ee/pull/4462

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
@austinchiang @brianchiu @kmaria @vicnate5 @xbrianlee
Hey Test Leads! I wrote a script that scans the poshi directory and counts the usages of each path and then removes the ones that are not used. Note that I check for locator2 as well as locator1.

**For static path calls**:
`<execute function="AssertTextEquals" locator1="Modal#HEADER" value1="Add Fragment" />`
I did a hard compare on both the file and path name. For example, for each locator with Modal#HEADER function or macro call, we increment the usage of Modal#HEADER by one.

**For dynamic path calls**
`<execute function="Type" locator1="AuditReports#ADVANCED_SEARCH_${reportFieldKey}_FIELD" value1="${searchTerm}" />`
I did a hard compare on the file and replaced what was contained in the variable field ${VAR} with a non-greedy quantifier .*? and performed a regex search. For example: the example above will become AuditReports#ADVANCED_SEARCH_.*?_FIELD . This assumes the variable can contain anything in order to not risk removing any used dynamic paths.

**Here is the list of unused and used path usages:**
https://gist.github.com/kyle-miho/18f36b712e567eb83dfb93f6dd0d4572
https://gist.github.com/kyle-miho/74300f7071d29272f6ec689398afa1e7

If you are okay with me removing unused paths from your component, let me know, and if you think I made a mistake or if you want to keep certain paths, let me know as well! Thanks!

**Comment by jpince** [comment]
@kyle-miho please make sure to scan the commerce sub repo https://github.com/liferay/com-liferay-commerce/tree/7.1.x/commerce-product-test/src/testFunctional. I think that's the only other place we have tests right now (outside of portal-web).
cc/ @iovaneale

**Comment by kyle-miho** [comment]
@jpince which branch from portal does commerce use with it? 7.1.x-head? master-head? 7.1.x ga1?

**Comment by jpince** [comment]
7.1.x head only. you don't need to worry about master.

**Comment by kyle-miho** [comment]
ci:test 
Now takes into account paths called from method selenium#.*?('Filename#Path')

**Comment by kyle-miho** [comment]
ci:test

**Pull request closed without merging**
