### PR TITLE
master-qa-14951

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-14951

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama 

Does it work with assertTextClickAtAndWait?

i was told that there's no difference between clickAt and clickAtAndWait in webdriver.

**Comment by evannagayama** [comment]
@brianchiu 

Ah, I see... I was just adding that as a precautionary pause. Since it doesn't do anything I'll take it out. Also we'll have to monitor the add wc because it's taking much longer now and we might have to just add a pause.

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25571

**Pull request closed without merging**
