### PR TITLE
master-qa-16761

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-16761

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Also, note that these changes need to be applied to the 6.2 and 6.1 branches. The commits can be cherry picked:
https://github.com/brianchiu/liferay-portal-ee/pull/4109
https://github.com/brianchiu/liferay-portal-ee/pull/4110
https://github.com/brianchiu/liferay-portal-ee/pull/4111
https://github.com/brianchiu/liferay-portal-ee/pull/4112

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/28161
https://github.com/brianchandotcom/liferay-portal-ee/pull/10675
https://github.com/brianchandotcom/liferay-portal-ee/pull/10676
https://github.com/brianchandotcom/liferay-portal-ee/pull/10677
https://github.com/brianchandotcom/liferay-portal-ee/pull/10678

**Pull request closed without merging**
