### PR TITLE
LPS-59249 - Form-groups shouldn't be nested within each other

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-59249

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@pat270 

If all tests pass, then this is safe to send up to Nate. If there are some failures, then we'll have to take a look.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@vicnate5 @ctampoya @brianwulbern @evannagayama

Can you help verify if this is a bug or fix the tests?

This fix is for:
https://issues.liferay.com/browse/LPS-59249

CC @pat270

**Comment by vicnate5** [comment]
@brianchiu @pat270 Based on the test results, looks like the html locator changed for ddm fields. Not a bug. But this will break a ton of tests if not fixed.

**Comment by brianchiu** [comment]
@pat270 @vicnate5 

What's the level of effort to fix this? If it's high, is there something that Patrick can do to make it better?

Either way, can you guys fix the tests so Pat can send this with those fixes to Nate?

**Comment by pat270** [comment]
@vicnate5 @brianchiu, the only requirement I have is form-groups shouldn't be nested.

**Comment by vicnate5** [comment]
@brianchiu @pat270 should be a low effect fix. I can fix and send to Nate.

**Comment by pat270** [comment]
@vicnate5 @brianchiu, awesome thanks guys!

**Comment by vicnate5** [comment]
Pushed to Nate
https://github.com/natecavanaugh/liferay-portal/pull/3618

**Comment by brianchiu** [comment]
@vicnate5 
Thanks, man.

**Pull request closed without merging**
