### PR TITLE
master-qa-16054

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-16054

### CODE REVIEW

**Comment by alee8888** [comment]
This is a resend of: https://github.com/brianchiu/liferay-portal/pull/475

**Comment by alee8888** [comment]
@brianchiu I'm checking.

**Comment by alee8888** [comment]
@brianchiu I fixed the "unsort" I did when I rebased.

**Comment by alee8888** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27932

**Pull request closed without merging**
