### PR TITLE
master-qa-15734

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-15734

### CODE REVIEW

**Comment by sharonchoi** [comment]
ci:retest

**Comment by brianchiu** [comment]
SF for SChoi.

@sharonchoi 
I'm going to...
1. Squash some of your commits
2. Rename "dm.vm.host.name" to "repository.vm.host.name"
3. Change the conditionals to look for documentum6 and sharepoint2010
4. Reword commits so that it's clear that you need to run the curl before plugin deploys

**Comment by brianchiu** [comment]
@sharonchoi 

I ended up re-doing the commits. Please see my pulls.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29119
https://github.com/brianchandotcom/liferay-portal-ee/pull/11046
https://github.com/brianchandotcom/liferay-portal-ee/pull/11047
https://github.com/brianchandotcom/liferay-portal-ee/pull/11048
https://github.com/brianchandotcom/liferay-portal-ee/pull/11049

**Pull request closed without merging**
