### PR TITLE
7.0.x-qa-27589

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-27589

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42979
https://github.com/brianchandotcom/liferay-portal/pull/42980

**Pull request closed without merging**
