### PR TITLE
master-qa-14249

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-14249

### CODE REVIEW

**Comment by brianchiu** [comment]
@alee8888 

How would this work on a specific Jenkins job like say tomcat mysql? Will all the other tests (for other databases) just fail?

**Comment by alee8888** [comment]
@brianchiu 

Every slave has all the databases already installed on each node and I checked the config.xml for Jenkins and regardless of the the job, database passwords are echoed into test.{hostname}.properties and database specific scripts are run. 

So it shouldn't matter if the work is specific to a tomcat/mysql job but you did bring up something that I need to check and that is if the table for each of the databases are cleared or not.

But just to be sure, I will check with the engineering team to confirm if other database tests on a tomcat/mysql specific job will fail.

**Comment by brianchiu** [comment]
@alee8888 

I'm going to take the non-poshi commits and backport this to 6.1.

**Comment by brianchiu** [comment]
SF for ALee.

@alee8888 

email goes after password. I re-ordered the properties echoes in build-test.xml

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25341
https://github.com/brianchandotcom/liferay-portal-ee/pull/9473
https://github.com/brianchandotcom/liferay-portal-ee/pull/9474
https://github.com/brianchandotcom/liferay-portal-ee/pull/9475
https://github.com/brianchandotcom/liferay-portal-ee/pull/9476

**Pull request closed without merging**
