### PR TITLE
master-en-27

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-13893

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama @brianwulbern 

Did you want to start writing macros in the new format now or continue writing in the old format and then change things later?

**Comment by brianwulbern** [comment]
@evannagayama @brianchiu 

I think it will be better for us to start updating to the new macro format in April and May.  Let's use the old format for now.  Thanks!

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25227

**Pull request closed without merging**
