### PR TITLE
LRQA-29510 | master

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-29510

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
StagingUsecase#StagingPublishPage doesn't pass. Do you want me to send in the other two tests and leave this one out? Or will you just resend this pull?

**Comment by kmaria** [comment]
ci:resend

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45365

**Pull request closed without merging**
