### PR TITLE
LPS-92258 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-92258

### CODE REVIEW

**Comment by kyle-miho** [comment]
This is a very quick test case, and may not cover all cases of pages finder, but covers a good amount of it for only one quick test case (we may want to rewrite this test into multiple later to expand the diversity of the test)
 [exec] BUILD SUCCESSFUL in 1m 41s  (doesnt include startup)
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
PR sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70422

**Pull request closed without merging**
