### PR TITLE
LPS-93364 Set namespaced referer plid to be able to get it in the journal portlet

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
previous results blocked because of test fix needed https://issues.liferay.com/browse/LRQA-48152

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
PR sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/71160

**Pull request closed without merging**
