### PR TITLE
LRQA-46992 Move path to where it belongs

### PR DESCRIPTION
**Pull request by brianchiu**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test

**Comment by austinchiang** [comment]
Made some changes and tested pull here: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=480561471

**Comment by austinchiang** [comment]
Pushed to BChan. https://github.com/brianchandotcom/liferay-portal/pull/68447

{{Type}} rewrites the entire text box, so I used {{KeyPress}} instead for appending the comma.

**Comment by brianchiu** [comment]
@austinchiang Thanks!

**Pull request closed without merging**
