### PR TITLE
LPS-90509 Updates tag to use new MultiSelect component and removes JSP dispatch

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchiu, this is an update on the `categories_selector` tag similar to the one done for the `tags_selector`.

Could you please see if tests pass or what adjustments need to get done?

screen shot 2019-03-01 at 20 37 24

/cc @kyle-miho, @liferay-continuous-integration

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
@jbalsas Thanks! I'll check it out.

**Comment by brianchiu** [comment]
@jbalsas I found one issue with the pull (but I think it's minor enough that I can still send this to BChan).

We've never been able to add categories on the spot before (usually we had to pre-create them). So I tried it out here.

I found that any category that's added from the "enter" or "comma" will not be saved, even if the category is an existing category. Should this be considered a bug? Or are you guys still developing this further?

cc @ealonso



Pull request sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/68844

**Comment by brianchiu** [comment]
Pull failed source formatting. Sending to Chema.
https://github.com/jbalsas/liferay-portal/pull/1677

**Pull request closed without merging**
