### PR TITLE
master-bw-115

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-19111

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama 

Reviewing JPince is helping us with WCM :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31870

**Comment by evannagayama** [comment]
@brianwulbern I think the gotoExportSiteCmd was intended to be used only in the macro, before we changed the convention. If they are both not necessary now, could you rename it to gotoExportSite instead of cmd? Thanks

**Comment by brianwulbern** [comment]
@evannagayama 

I wanted to do that too.  The problem is that gotoExportSiteCmd is getting called from other blocks within the LAR macro _and_ from outside of the macro.  If the convention now is to just drop the Cmd part, we can do that - but the original intention behind using it is still partially in place in LAR.macro.  At least, it is, until the file gets a more substantial face-lift.  Remove it, still?

**Comment by evannagayama** [comment]
The new convention is like this "_editName", there are some in Calendar.macro. There are a couple options on how to change it that wouldn't require too much effort, I think... Also I think either way we should get rid of the cmd.

Can you let maria know when you fix it, because this will affect her tests. Thanks.

**Comment by brianwulbern** [comment]
@evannagayama 

Made a ticket for that task here: https://issues.liferay.com/browse/LRQA-19243

**Pull request closed without merging**
