### PR TITLE
master-en-69

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-8101

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
SF for ENagayama / KGai.

@evannagayama @koor4356 
Changed the select button locator to be more generic.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26131

**Pull request closed without merging**
