### PR TITLE
master-qa-14946

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-14946

### CODE REVIEW

**Comment by brianchiu** [comment]
@evannagayama 

```
		<while>
			<condition function="IsVisible" locator1="PGDocumentsandmediaDocument#UP_BUTTON" />
			<then>
				<execute function="Click" locator1="PGDocumentsandmediaDocument#UP_BUTTON" />
			</then>
		</while>
```

Does this work consistently? If yes, I'll leave it like this, but it feels safer to add a pause after the click.

**Comment by evannagayama** [comment]
@brianchiu, I'll add a pause.

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25571

**Pull request closed without merging**
