### PR TITLE
master-qa-20843

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-20843

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
I'm retesting this because of that CPSitepages#DeleteSitePages failure.

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34102

**Pull request closed without merging**
