### PR TITLE
master-qa-19122

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-19122

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama

CPWebcontent fixes

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianwulbern @evannagayama

I want to wait for the results to come back. Please send directly to BChan if it passes on Monday. The changes look fine to me.

**Comment by brianchiu** [comment]
CC @kiyoshilee

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31946

**Pull request closed without merging**
