### PR TITLE
LRQA-25108 Test DB2 upgrade

### PR DESCRIPTION
**Pull request by pyoo47**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
All the other parts of DB2 upgrade testing have been merged. I've backed out my testing code that downloads the DB2 zip files from mirrors. Once you've confirmed that the DB2 upgrade test passes, you can cherry pick the LRQA-25729 commit in this pull and send to BChan.

ci:retest

**Comment by pyoo47** [comment]
ci:retest (create-bare)

**Comment by brianchiu** [comment]
@pyoo47 @vicnate5
Still failed in the same way.

Victor/Peter - do we know for sure that the dump is good? Is there a way to verify that the poshi test to generate the database dump pre-upgrade passed successfully?

**Comment by pyoo47** [comment]
I need to recreate the dump file using the create-bare.sql. I’ve been sidelined by problems with the release tester. I’ll try to get to it tomorrow.

Peter

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest - This retest should include create-bare.sql based DB2 data dumps for both 6.1.2 and 6.2.3.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by vicnate5** [comment]
I don't think the create-bare fixed the issue :(
This might be something else in our setup.

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by vicnate5** [comment]
@pyoo47 You can close this branch :)

**Pull request closed without merging**
