### PR TITLE
master-bw-12

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-17146

### CODE REVIEW

**Comment by brianchiu** [comment]
@brianwulbern 

Portal Smoke test failure?

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@brianchiu, I updated the locator scope - this works locally so it should work on ci

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/28955

**Pull request closed without merging**
