### PR TITLE
master-kg-5

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-17034

### CODE REVIEW

**Comment by koor4356** [comment]
SF for @anthony-chu 
- Change Click#clickAt to just Click.

**Comment by brianchiu** [comment]
SF for AChu / KGai.

@koor4356 @anthony-chu 
I fixed the typo "messaage" in the commit.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/28722

**Comment by brianchiu** [comment]
@koor4356 @anthony-chu 

I missed this...
https://github.com/koor4356/liferay-portal/commit/e184b931288e835ea54ea86551b98204d3631c39

"LQRA" should be "LRQA"

**Pull request closed without merging**
