### PR TITLE
LPS-95913 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-95913

### CODE REVIEW

**Comment by brianchiu** [comment]
@kyle-miho include the freemarker fragment source

**Comment by kyle-miho** [comment]
@brianchiu going to do this after i send jurgen back a pull

**Comment by kyle-miho** [comment]
@brianchiu updated

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
PR submitted to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74159
https://github.com/brianchandotcom/liferay-portal-ee/pull/24864

**Pull request closed without merging**
