### PR TITLE
master-qa-21359

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-21359

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@brianchiu 

The top two failures are flukes from flaky tests, the PGStaging ones are going to be addressed in https://issues.liferay.com/browse/LRQA-21381

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34791

**Pull request closed without merging**
