### PR TITLE
master-qa-21363

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-21363

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5 
Since this affects workflow stuff, is this safe to merge?

**Comment by vicnate5** [comment]
@brianchiu Looks good. Safe to merge.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34785

**Comment by brianchiu** [comment]
@kmaria 
This conflicted with a later commit that @anthony-chu made here:
https://github.com/anthony-chu/liferay-portal/commit/f255876154926f29a475cf01e66f4ec579f0658d

So I'm removing the commit that affected the WebContent.macro and resending to BChan.

**Pull request closed without merging**
