### PR TITLE
master-en-104

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-9441

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
@evannagayama @brianwulbern 

Please fix your commit message casing (addCP) and resend
"LRQA-9441 Optimize Category#addcp macro to allow looping"

**Comment by evannagayama** [comment]
@brianchiu I updated the pr here: https://github.com/brianchiu/liferay-portal/pull/311

**Pull request closed without merging**
