### PR TITLE
master-al-10

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-17343

### CODE REVIEW

**Comment by brianchiu** [comment]
@alee8888 
Please fix. See error above.

**Comment by alee8888** [comment]
@brianchiu sorry fixed the error and force pushed the branch. Thanks

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29248

**Pull request closed without merging**
