### PR TITLE
master-qa-19989

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-19989

### CODE REVIEW

**Comment by brianchiu** [comment]
@sharonchoi
Can you review and push this? My repo has been corrupted so I can't pull this in right now.

**Comment by sharonchoi** [comment]
@brianchiu ok will do.

**Comment by sharonchoi** [comment]
SF for MKispal:
-functionality in DM portlet changed so that you have to enable configurations in order for actions and navigation buttons to show up, so I updated the test to do so
-there are new locators for the management bar implemented for lexicon
-updated macros to use new locators

**Comment by sharonchoi** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/32990

**Comment by brianchiu** [comment]
@sharonchoi 
Thanks!

**Pull request closed without merging**
