### PR TITLE
master-qa-22871

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-22871

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kmaria 
Just trying to figure out how consistent the failures are. Normally I try not to retest so much.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37157

**Pull request closed without merging**
