### PR TITLE
master-qa-17407

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-17407

### CODE REVIEW

**Comment by brianchiu** [comment]
@brianwulbern
Can you take a look at this? I can't get to this today, so might as well have you look.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@brianchiu 
The locator looks good, and with all those changes in effect, Anthony uploaded a passing Smoke test's index.html to LRQA-17407.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29382

**Comment by brianchiu** [comment]
@anthony-chu @brianwulbern 

Anthony, can you see if you've set your affiliation to the liferay organization as public? The PR tester won't run if you haven't done this.

See https://help.github.com/articles/publicizing-or-hiding-organization-membership/

**Comment by anthony-chu** [comment]
@brianchiu Thanks, I've updated my github organization settings to public.

**Pull request closed without merging**
