### PR TITLE
master-sc-31

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-13970

### CODE REVIEW

**Comment by brianchiu** [comment]
Pushed back to SChoi / SPark.

@sharonchoi @simonkpark 
Please resend with a more generic Link.path locator. Something that involves "//a".

Get input from @kenjiheigel from this as well.

Since the RSS/Subscribe show up in multiple places together -> it might be a uisection and not a uielement.

**Comment by kenjiheigel** [comment]
I think uielements is the correct location. We want to group them by the smallest criteria first. i.e. it classifies as a link before it classifies into a section. 

The uisections should be used to contain things that we can't isolate to a particular element type, such as specific CKEditor locators, other elements that don't fall into those categories, or if it does fall into that element type but needs something specific to identify it (like using additional parent tags/attributes in the xpath to denote it to a specific part/section of the page)

**Comment by brianchiu** [comment]
@sharonchoi @kenjiheigel @simonkpark 

Do all links have that taglib text part?

```
//a/span[contains(@class,'taglib-text') and contains(.,'Subscribe')]
```

**Comment by kenjiheigel** [comment]
@brianchiu @sharonchoi @simonkpark 

Links vary across portal, because they can be created through a variety of taglibs. Because of this, I think the ideal format for Link.path (```//a[contains(.,'Link Name')]```) may not always be possible.
In this case, the links that Simon is trying to add should still go into Link.path, and it can keep its existing xpath. It needs the child "span" tag in the xpath though, because if not, a normal assertText will not work for these, because there's other inner text within the anchor.

**Comment by brianchiu** [comment]
@sharonchoi @kenjiheigel @simonkpark 

Alright. I will push this like this.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26180

**Pull request closed without merging**
