### PR TITLE
LRQA-44473 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-44473

master only

### CODE REVIEW

**Comment by kyle-miho** [comment]
@brianchiu I made a few minor changes after retesting, so lets wait for ci:test to pass first if possible

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
This is master only, unless if we cherry-pick everything except LRQA-44473 Reenable fixed acceptance tests.
There might be some other differences in 7.1.x. But if we do not backport this, then this will be where 7.1.x and master officially diverge for JSON WS API.

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64660

**Pull request closed without merging**
