### PR TITLE
LPS-93807 Fix compile issues

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchiu, this is the PR that was reverted last week. Sending it to you first to see if everything is okay.

Thanks

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Looks good. I don't see any trace of the error from https://issues.liferay.com/browse/LPS-94659.

Testray results: https://testray.liferay.com/home/-/testray/case_results/index?testrayBuildId=566233216&cur=1&delta=20

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
PR submitted to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72515

**Pull request closed without merging**
