### PR TITLE
master-qa-28389

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-28389

### CODE REVIEW

**Comment by kmaria** [comment]
ci:stop

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44033
https://github.com/brianchandotcom/liferay-portal/pull/44034

**Pull request closed without merging**
