### PR TITLE
master-qa-17599

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-17599

### CODE REVIEW

**Comment by sharonchoi** [comment]
@brianchiu more pulls coming, please don't close out LRQA ticket

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@sharonchoi 

I moved one of your IFRAME changes from the first commit to the second commit.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29691

**Pull request closed without merging**
