### PR TITLE
LRQA-49529 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-49529

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:poshi

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
PR submitted to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74217
https://github.com/brianchandotcom/liferay-portal-ee/pull/24890

**Pull request closed without merging**
