### PR TITLE
master-qa-25989

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-25989

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@patriciajeanperez 
Didn't you quarantine this test? You'll have to either check Testray after these results come back or un-quarantine it to see the results in the github reports here.

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Pull request closed without merging**
