### PR TITLE
master-qa-16334

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-16334

### CODE REVIEW

**Comment by evannagayama** [comment]
@brianchiu,

This pr cannot be cherry-picked with the 6.2 branches because the staging.macro is different between them

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27490
https://github.com/brianchandotcom/liferay-portal-ee/pull/10454
https://github.com/brianchandotcom/liferay-portal-ee/pull/10455

**Pull request closed without merging**
