### PR TITLE
LPS-57558.persist

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-17212

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by juliocamarero** [comment]
awesome! :+1: 

thanks @brianwulbern!!

**Comment by juliocamarero** [comment]
@brianchiu could you please send this pull request today? I have some others that depend on this one. Thanks a lot!! :)

**Comment by brianchiu** [comment]
@juliocamarero 

Sure thing. On it right now.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29008

**Pull request closed without merging**
