### PR TITLE
7.0.x-qa-29131

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-29131

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
@brianchiu  oh... could you please advise? :)

**Comment by brianchiu** [comment]
@kmaria 
It looks fine to me. I didn't get any source formatter errors when I tried it.

Only change I made was removing the space at the last comment.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44837

**Pull request closed without merging**
