### PR TITLE
LPS-90059 Implements table view

### PR DESCRIPTION
**Pull request by ealonso**
Hey @brianchiu @kyle-miho

I've updated the views, table and title list, for asset publisher.

Could you please take a look at it?

Thanks!!

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@kyle-miho can you take this one tomorrow when you have a chance?

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@kyle-miho @brianchiu 

Sending it to Brian since the errors are not related with this pull https://github.com/brianchandotcom/liferay-portal/pull/68290

**Comment by brianchiu** [comment]
@ealonso Yeah. From taking a look, it seems the test failures are not related.

**Pull request closed without merging**
