### PR TITLE
LRQA-42406 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-42406
7.1.x: https://github.com/brianchiu/liferay-portal-ee/pull/4463

### CODE REVIEW

**Comment by kyle-miho** [comment]
./cc @austinchiang @brianchiu @kmaria @vicnate5 @xbrianlee @alexcandidos @john-co
@jpince @reizero00 @brianwulbern

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64526
https://github.com/brianchandotcom/liferay-portal-ee/pull/22135

**Pull request closed without merging**
