### PR TITLE
LRQA-44420 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-44420

backport to 7.1

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test

**Comment by brianchiu** [comment]
ci:test:sf

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/64706
https://github.com/brianchandotcom/liferay-portal-ee/pull/22226

**Pull request closed without merging**
