### PR TITLE
master-qa-17359

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-17359

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5 

Does this need to go into 7.0.x as well?

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29214

**Comment by vicnate5** [comment]
@brianchiu I am assuming stuff that affects the acceptance layer is the only thing that needs to go into 7.0.x at this point. This pull does not affect anything for M7.

**Comment by brianchiu** [comment]
@vicnate5 

kk

**Pull request closed without merging**
