### PR TITLE
master-vw-qa-19988

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-19988

@kmaria

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged please re-run this particular pull request.

Sorry for the inconvenience.

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchiu** [comment]
Thanks, @vicnate5

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34355

**Pull request closed without merging**
