### PR TITLE
LRQA-32822 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Master removal of For loops https://issues.liferay.com/browse/LRQA-32822
Master convert FW conditionals https://issues.liferay.com/browse/LRQA-32827

If this combines with other stuff without conflicts, I am gonna be amazed. Let me know if you need help.

### CODE REVIEW

**Comment by vicnate5** [comment]
@anthony-chu There is one <for> loop left in CPSitepages#AddPagesFullPageApplication. I was not sure how to convert this one. Could you take a look?

**Comment by anthony-chu** [comment]
thanks @vicnate5. i'll take a look into it under [LRQA-32905](https://issues.liferay.com/browse/LRQA-32905).

**Comment by vicnate5** [comment]
err I found a problem with one of the commits. Will resend tomorrow morning.

**Comment by vicnate5** [comment]
resent https://github.com/brianchiu/liferay-portal/pull/1577

**Pull request closed without merging**
