### PR TITLE
master-sc-11

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-14347

### CODE REVIEW

**Comment by sharonchoi** [comment]
@brianchiu test will fail on master due to LPS-54469

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal-ee/pull/9338
https://github.com/brianchandotcom/liferay-portal-ee/pull/9337
 https://github.com/brianchandotcom/liferay-portal/pull/25106

**Pull request closed without merging**
