### PR TITLE
master-qa-14915

### PR DESCRIPTION
**Pull request by jaredzimmerman1**
https://issues.liferay.com/browse/LRQA-14915

### CODE REVIEW

**Comment by jaredzimmerman1** [comment]
@kenjiheigel

I've added the following paths to PGCalendar.path:
- SMALL_CALENDAR_SPECIFIC_DAY
- SMALL_CALENDAR_SPECIFIC_BUSY_DAY
- SCHEDULER_SPECIFIC_DAY
- SCHEDULER_EVENT_DIALOG_BOX_WHEN_LABEL
- SCHEDULER_EVENT_DIALOG_BOX_WHEN_FIELD
- SCHEDULER_EVENT_DIALOG_BOX_CALENDAR_LABEL

**Comment by brianchiu** [comment]
@jaredzimmerman1 

Rebase error?

**Comment by jaredzimmerman1** [comment]
@brianchiu

Fixed errors and pushed to origin.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
SF for JZimmerman.

@jaredzimmerman1 
Added some spaces, changed one of your paths to use single quotes and "xpath" instead of "xPath".

We also shouldn't use "isset" unless we need to type it or pass it in some other way. Otherwise if the variable is a toggle, we should use true/false. I changed this as well.

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25801
https://github.com/brianchandotcom/liferay-portal-ee/pull/9709
https://github.com/brianchandotcom/liferay-portal-ee/pull/9710

**Pull request closed without merging**
