### PR TITLE
master-qa-15608

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-15608

### CODE REVIEW

**Comment by evannagayama** [comment]
I'll use the new commit convention on my next pr. I had too much work already done and random issues I ran into for this one.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@evannagayama 

How come the test.properties changes are only for master?

**Comment by evannagayama** [comment]
These are part of the osgi extraction and the test.properties are set just for this so that they can be in a separate run than portal-wcm.

**Comment by brianchiu** [comment]
ok.

Do Jenkins jobs need to be created for these? @kiyoshilee
https://github.com/evannagayama/liferay-portal/commit/3f8fab53698de842f96ab4a88531e34bde52f80a

**Comment by evannagayama** [comment]
I created this task ticket: https://issues.liferay.com/browse/LRQA-15668. Could we also have a jenkins reset after this goes in so that the other osgi portlets are running (ie rss, xss, etc)?

**Comment by evannagayama** [comment]
@brianchiu 
I talked to Kiyoshi and he suggested I cherry-pick it even if it won't be technically used. Here are the pr's:
https://github.com/brianchiu/liferay-portal-ee/pull/3884
https://github.com/brianchiu/liferay-portal-ee/pull/3885

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/26605
https://github.com/brianchandotcom/liferay-portal-ee/pull/10035
https://github.com/brianchandotcom/liferay-portal-ee/pull/10036
https://github.com/brianchandotcom/liferay-portal-ee/pull/10037
https://github.com/brianchandotcom/liferay-portal-ee/pull/10038

**Pull request closed without merging**
